interface CategoryOption {
  category: string;
  options: string[];
}

export const CATEGORY_OPTIONS: Record<string, CategoryOption> = {
  movies: {
    category: "TV Shows & Movies",
    options: [
      "Breaking Bad",
      "The Office",
      "Friends",
      "Stranger Things",
      "Game of Thrones",
      "Star Wars",
      "Harry Potter",
      "The Matrix",
      "Jurassic Park",
      "The Lion King",
      "Titanic",
      "Avatar",
      "The Avengers",
      "Lord of the Rings",
      "Finding Nemo",
      "The Simpsons",
      "Seinfeld",
      "The Walking Dead",
      "Black Mirror",
      "Squid Game",
      "Inception",
      "Forrest Gump",
      "The Godfather",
      "Pulp Fiction",
      "Fight Club",
      "The Dark Knight",
      "Jaws",
      "E.T.",
      "Back to the Future",
      "Indiana Jones",
      "The Shawshank Redemption",
      "The Wizard of Oz",
      "Ghostbusters",
      "The Terminator",
      "Toy Story",
      "The Silence of the Lambs",
      "Gladiator",
      "The Big Bang Theory",
      "How I Met Your Mother",
      "Modern Family",
      "The Crown",
      "Bridgerton",
      "The Mandalorian",
      "The Last of Us",
      "Wednesday",
      "The Boys",
      "Better Call Saul",
      "Dexter",
      "Lost",
      "The Wire",
      "Mad Men",
      "The Sopranos",
      "Frasier",
      "Cheers",
      "The X-Files",
      "Twin Peaks",
      "The Twilight Zone",
      "The Good Place",
      "Parks and Recreation",
      "Brooklyn Nine-Nine",
      "The Office UK",
      "Downton Abbey",
      "Westworld",
      "True Detective",
      "Chernobyl",
      "Band of Brothers",
      "The Pacific",
      "Planet Earth",
      "Blue Planet",
      "Cosmos",
      "The Witcher",
      "House of the Dragon",
      "Succession",
      "Ted Lasso",
      "Abbott Elementary",
      "Schitt's Creek",
      "The Bear",
      "Fleabag",
      "Killing Eve",
      "Ozark",
      "Narcos",
      "Money Heist",
      "Dark",
      "The Umbrella Academy",
      "Daredevil",
      "Jessica Jones",
      "WandaVision",
      "Loki",
      "Moon Knight",
      "Ms. Marvel",
      "Andor",
      "House of Cards",
      "The Americans",
      "Homeland",
      "24",
      "Prison Break",
      "Grey's Anatomy",
      "ER",
      "House",
      "The Good Doctor",
      "This Is Us",
      "The Handmaid's Tale",
      "Black Books",
      "Father Ted",
      "The IT Crowd",
      "Peep Show",
    ],
  },
  disney: {
    category: "Disney Characters",
    options: [
      "Mickey Mouse",
      "Donald Duck",
      "Goofy",
      "Minnie Mouse",
      "Snow White",
      "Cinderella",
      "Ariel",
      "Belle",
      "Jasmine",
      "Aurora",
      "Tiana",
      "Merida",
      "Aladdin",
      "Simba",
      "Timon",
      "Pumbaa",
      "Woody",
      "Buzz Lightyear",
      "Nemo",
      "Dory",
      "Elsa",
      "Anna",
      "Olaf",
      "Moana",
      "Mulan",
      "Peter Pan",
      "Captain Hook",
      "Tinker Bell",
      "Winnie the Pooh",
      "Tigger",
      "Piglet",
      "Eeyore",
      "Bambi",
      "Dumbo",
      "Pinocchio",
      "Jiminy Cricket",
      "Mowgli",
      "Baloo",
      "Rapunzel",
      "Flynn Rider",
      "Hercules",
      "Megara",
      "Pocahontas",
      "John Smith",
      "Tarzan",
      "Jane Porter",
      "Stitch",
      "Lilo",
      "Raya",
      "Mirabel",
      "Bruno",
      "Princess Elena",
      "Sofia the First",
      "Vanellope",
      "Ralph",
      "Judy Hopps",
      "Nick Wilde",
      "Baymax",
      "Hiro",
      "Wall-E",
      "Eve",
    ],
  },
  superheroes: {
    category: "Superheroes",
    options: [
      "Spider-Man",
      "Batman",
      "Superman",
      "Wonder Woman",
      "Iron Man",
      "Captain America",
      "Thor",
      "Hulk",
      "Black Widow",
      "Black Panther",
      "Doctor Strange",
      "Wolverine",
      "Deadpool",
      "Flash",
      "Aquaman",
      "Captain Marvel",
      "Hawkeye",
      "Scarlet Witch",
      "Loki",
      "Thanos",
      "Star-Lord",
      "Groot",
      "Rocket Raccoon",
      "Professor X",
      "Magneto",
      "Storm",
      "Jean Grey",
      "Daredevil",
      "Ghost Rider",
      "Venom",
      "Joker",
      "Harley Quinn",
      "Catwoman",
      "Penguin",
      "Riddler",
      "Poison Ivy",
      "Lex Luthor",
      "Winter Soldier",
      "Doctor Octopus",
      "Mysterio",
    ],
  },
  celebrities: {
    category: "Celebrities",
    options: [
      "Tom Hanks",
      "Morgan Freeman",
      "Leonardo DiCaprio",
      "Brad Pitt",
      "Jennifer Lawrence",
      "Meryl Streep",
      "Will Smith",
      "Johnny Depp",
      "Taylor Swift",
      "Beyoncé",
      "Lady Gaga",
      "Justin Bieber",
      "Drake",
      "Adele",
      "Ed Sheeran",
      "Rihanna",
      "Barack Obama",
      "Donald Trump",
      "Elon Musk",
      "Bill Gates",
      "Mark Zuckerberg",
      "Oprah Winfrey",
      "Ellen DeGeneres",
      "Jimmy Fallon",
      "Gordon Ramsay",
      "David Beckham",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Michael Jordan",
      "LeBron James",
      "Serena Williams",
      "Michael Phelps",
      "Albert Einstein",
      "Stephen Hawking",
      "Pablo Picasso",
      "Vincent van Gogh",
      "Madonna",
      "Michael Jackson",
      "Elvis Presley",
      "Bob Marley",
      "Ariana Grande",
      "Bruno Mars",
      "Katy Perry",
      "Eminem",
      "Kanye West",
      "Kim Kardashian",
      "Jennifer Aniston",
      "Robert Downey Jr",
      "Chris Hemsworth",
      "Scarlett Johansson",
      "Dwayne Johnson",
      "Ryan Reynolds",
      "Emma Watson",
      "Daniel Radcliffe",
      "Justin Timberlake",
      "Britney Spears",
      "Selena Gomez",
      "Miley Cyrus",
      "Zendaya",
      "Tom Holland",
      "Billie Eilish",
      "Post Malone",
      "Cardi B",
      "Kendrick Lamar",
      "Harry Styles",
      "Chris Pratt",
      "Margot Robbie",
      "Gal Gadot",
      "Keanu Reeves",
      "Tom Cruise",
    ],
  },
  animals: {
    category: "Animals",
    options: [
      "Lion",
      "Elephant",
      "Giraffe",
      "Monkey",
      "Penguin",
      "Kangaroo",
      "Koala",
      "Panda",
      "Tiger",
      "Bear",
      "Wolf",
      "Fox",
      "Deer",
      "Zebra",
      "Hippopotamus",
      "Rhinoceros",
      "Crocodile",
      "Snake",
      "Eagle",
      "Owl",
      "Parrot",
      "Flamingo",
      "Octopus",
      "Dolphin",
      "Shark",
      "Whale",
      "Butterfly",
      "Spider",
      "Ant",
      "Bee",
      "Sloth",
      "Platypus",
      "Peacock",
      "Ostrich",
      "Gorilla",
      "Cheetah",
      "Camel",
      "Seal",
      "Polar Bear",
      "Penguin",
      "Hamster",
      "Guinea Pig",
      "Rabbit",
      "Cat",
      "Dog",
      "Horse",
      "Cow",
      "Pig",
      "Sheep",
      "Goat",
      "Chicken",
      "Rooster",
      "Duck",
      "Goose",
      "Turkey",
      "Pigeon",
      "Seagull",
      "Crow",
      "Raven",
      "Blue Jay",
      "Cardinal",
      "Hummingbird",
      "Woodpecker",
      "Pelican",
      "Swan",
      "Toucan",
      "Macaw",
      "Cockatoo",
      "Iguana",
      "Chameleon",
      "Gecko",
      "Turtle",
      "Tortoise",
      "Frog",
      "Toad",
      "Salamander",
      "Newt",
      "Fish",
      "Goldfish",
      "Clownfish",
      "Seahorse",
      "Starfish",
      "Jellyfish",
      "Crab",
      "Lobster",
      "Shrimp",
      "Squid",
      "Snail",
      "Slug",
      "Ladybug",
      "Praying Mantis",
      "Grasshopper",
      "Cricket",
      "Caterpillar",
      "Dragonfly",
      "Mosquito",
      "Fly",
      "Wasp",
      "Hornet",
      "Scorpion",
      "Tarantula",
      "Centipede",
      "Millipede",
      "Raccoon",
      "Skunk",
      "Squirrel",
      "Chipmunk",
      "Beaver",
      "Otter",
      "Badger",
      "Hedgehog",
      "Armadillo",
      "Opossum",
      "Mole",
      "Bat",
      "Lemur",
      "Meerkat",
      "Hyena",
      "Jaguar",
      "Leopard",
      "Panther",
      "Lynx",
      "Bobcat",
      "Mountain Lion",
      "Donkey",
      "Mule",
      "Zebra",
      "Buffalo",
      "Bison",
      "Moose",
      "Elk",
      "Reindeer",
      "Antelope",
      "Gazelle",
      "Wildebeest",
      "Warthog",
      "Llama",
      "Alpaca",
      "Yak",
    ],
  },
  food: {
    category: "Food",
    options: [
      "Pizza",
      "Hamburger",
      "Sushi",
      "Spaghetti",
      "Taco",
      "Ice Cream",
      "Chocolate Cake",
      "French Fries",
      "Hot Dog",
      "Pancakes",
      "Waffles",
      "Donut",
      "Cookie",
      "Sandwich",
      "Salad",
      "Soup",
      "Steak",
      "Chicken Wings",
      "Burrito",
      "Nachos",
      "Popcorn",
      "Apple Pie",
      "Cupcake",
      "Croissant",
      "Ramen",
      "Fried Rice",
      "Curry",
      "Lasagna",
      "Mac and Cheese",
      "Meatballs",
      "Fish and Chips",
      "Pho",
      "Dim Sum",
      "Pad Thai",
      "Guacamole",
      "Paella",
      "Sushi Roll",
      "Kimchi",
      "Hummus",
      "Falafel",
      "Tandoori Chicken",
      "Butter Chicken",
      "Biryani",
      "Gyoza",
      "Spring Rolls",
      "Baklava",
      "Tiramisu",
      "Gelato",
      "Pierogi",
      "Schnitzel",
      "Gnocchi",
      "Couscous",
      "Shawarma",
      "Borscht",
      "Poutine",
      "Churros",
      "Empanadas",
      "Tamales",
      "Ceviche",
      "Moussaka",
      "Spanakopita",
    ],
  },
  songs: {
    category: "Pop Songs",
    options: [
      "Bohemian Rhapsody",
      "Thriller",
      "Sweet Dreams",
      "Dancing Queen",
      "Billie Jean",
      "Like a Prayer",
      "Sweet Child O' Mine",
      "Smells Like Teen Spirit",
      "I Will Always Love You",
      "Stayin' Alive",
      "Sweet Caroline",
      "Hey Jude",
      "Purple Rain",
      "Hotel California",
      "Imagine",
      "Sweet Home Alabama",
      "Don't Stop Believin'",
      "I Want to Hold Your Hand",
      "Uptown Funk",
      "Shape of You",
      "Rolling in the Deep",
      "Bad Guy",
      "Shake It Off",
      "Despacito",
      "Old Town Road",
      "Blinding Lights",
      "Watermelon Sugar",
      "Bad Romance",
      "Call Me Maybe",
      "Happy",
      "All Star",
      "Poker Face",
      "Firework",
      "Someone Like You",
      "Party Rock Anthem",
      "Get Lucky",
      "Royals",
      "All About That Bass",
      "See You Again",
      "Hello",
      "Closer",
      "Havana",
      "Thank U, Next",
      "Truth Hurts",
      "Levitating",
      "drivers license",
      "Stay",
      "As It Was",
      "Anti-Hero",
      "Hey There Delilah",
      "Umbrella",
      "Low",
      "Just Dance",
      "I Gotta Feeling",
      "Tik Tok",
      "California Gurls",
      "Rolling in the Deep",
      "We Found Love",
      "Gangnam Style",
      "Wrecking Ball",
      "Happy",
      "Blank Space",
      "Hotline Bling",
      "Sorry",
      "One Dance",
      "God's Plan",
      "Shallow",
      "7 Rings",
      "Dynamite",
    ],
  },
  accents: {
    category: "Accents & Impressions",
    options: [
      "British Accent",
      "Australian Accent",
      "Irish Accent",
      "Scottish Accent",
      "French Accent",
      "Italian Accent",
      "Russian Accent",
      "German Accent",
      "Spanish Accent",
      "Indian Accent",
      "Southern US Accent",
      "New York Accent",
      "Boston Accent",
      "Valley Girl",
      "Surfer Dude",
      "Cowboy",
      "Robot Voice",
      "Elvis Presley",
      "Arnold Schwarzenegger",
      "Donald Trump",
      "Morgan Freeman",
      "Sean Connery",
      "Christopher Walken",
      "Yoda",
      "Darth Vader",
      "Mickey Mouse",
      "Kermit the Frog",
      "Batman",
      "Pirate",
      "Dracula",
      "Gollum",
      "Homer Simpson",
      "Peter Griffin",
      "SpongeBob SquarePants",
      "Shrek",
      "Borat",
      "Queen Elizabeth",
      "Barack Obama",
      "David Attenborough",
      "Gordon Ramsay",
    ],
  },
  historical: {
    category: "Historical Figures",
    options: [
      "Albert Einstein",
      "Leonardo da Vinci",
      "William Shakespeare",
      "Napoleon Bonaparte",
      "Abraham Lincoln",
      "George Washington",
      "Martin Luther King Jr.",
      "Winston Churchill",
      "Marie Curie",
      "Cleopatra",
      "Julius Caesar",
      "Alexander the Great",
      "Mozart",
      "Beethoven",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Charles Darwin",
      "Isaac Newton",
      "Galileo Galilei",
      "Thomas Edison",
      "Benjamin Franklin",
      "Florence Nightingale",
      "Joan of Arc",
      "Christopher Columbus",
      "Marco Polo",
      "Genghis Khan",
      "Leonardo da Vinci",
      "Michelangelo",
      "Queen Victoria",
      "Henry VIII",
      "Nelson Mandela",
      "Mahatma Gandhi",
      "Mother Teresa",
      "Anne Frank",
      "Rosa Parks",
      "Helen Keller",
      "Wright Brothers",
      "Neil Armstrong",
      "Charlie Chaplin",
      "Walt Disney",
      "Aristotle",
      "Plato",
      "Socrates",
      "King Tut",
      "Catherine the Great",
      "Queen Elizabeth I",
      "Confucius",
      "Sun Tzu",
      "Nikola Tesla",
      "Marie Antoinette",
      "Harriet Tubman",
      "Susan B. Anthony",
      "Frederick Douglass",
      "Eleanor Roosevelt",
      "Louis Pasteur",
      "Sigmund Freud",
      "Jane Austen",
      "Ernest Hemingway",
      "Mark Twain",
      "Charles Dickens",
      "Frida Kahlo",
      "Mary Shelley",
      "Virginia Woolf",
      "Emily Dickinson",
      "Maya Angelou",
      "Ada Lovelace",
      "Amelia Earhart",
      "George Orwell",
      "Franz Kafka",
      "Oscar Wilde",
      "Edgar Allan Poe",
      "Emily Brontë",
      "Charlotte Brontë",
      "Mary Wollstonecraft",
      "René Descartes",
      "John Locke",
      "Karl Marx",
      "Friedrich Nietzsche",
      "Jean-Jacques Rousseau",
      "Voltaire",
      "Mary Queen of Scots",
      "Elizabeth Blackwell",
      "Clara Barton",
      "Pocahontas",
      "Sacagawea",
      "Sitting Bull",
      "Crazy Horse",
      "Geronimo",
      "Chief Joseph",
      "Booker T. Washington",
      "W.E.B. Du Bois",
      "Malcolm X",
      "Thurgood Marshall",
      "Jackie Robinson",
      "Jesse Owens",
      "Muhammad Ali",
      "Princess Diana",
      "Mother Jones",
      "Margaret Thatcher",
      "Indira Gandhi",
      "Golda Meir",
    ],
  },
  geography: {
    category: "Geography",
    options: [
      "Mount Everest",
      "Grand Canyon",
      "Great Barrier Reef",
      "Amazon Rainforest",
      "Sahara Desert",
      "Niagara Falls",
      "Venice",
      "Paris",
      "London",
      "New York City",
      "Tokyo",
      "Sydney",
      "Rio de Janeiro",
      "Cairo",
      "Rome",
      "Great Wall of China",
      "Taj Mahal",
      "Machu Picchu",
      "Petra",
      "Stonehenge",
      "Victoria Falls",
      "Dead Sea",
      "Mount Fuji",
      "Yellowstone",
      "Antarctica",
      "Hawaii",
      "Iceland",
      "Swiss Alps",
      "Galapagos Islands",
      "Maldives",
      "Northern Lights",
      "Nile River",
      "Mount Kilimanjaro",
      "Great Plains",
      "Andes Mountains",
      "Mediterranean Sea",
      "Pacific Ocean",
      "Himalayas",
      "Serengeti",
      "Great Lakes",
      "California",
      "Texas",
      "Florida",
      "New York",
      "Alaska",
      "Montana",
      "Colorado",
      "Louisiana",
      "Massachusetts",
      "Arizona",
      "Nevada",
      "Oregon",
      "Washington",
      "Maine",
      "Brazil",
      "France",
      "Italy",
      "Spain",
      "Germany",
      "China",
      "Japan",
      "India",
      "Russia",
      "Australia",
      "Mexico",
      "Canada",
      "Egypt",
      "South Africa",
      "Argentina",
      "Greece",
      "Thailand",
      "Vietnam",
      "Morocco",
      "Peru",
      "Amsterdam",
      "Berlin",
      "Dubai",
      "Hong Kong",
      "Istanbul",
      "Jerusalem",
      "Las Vegas",
      "Moscow",
      "Mumbai",
      "Prague",
      "San Francisco",
      "Seoul",
      "Shanghai",
      "Singapore",
      "Stockholm",
    ],
  },
  books: {
    category: "Books",
    options: [
      "Harry Potter",
      "The Lord of the Rings",
      "Pride and Prejudice",
      "To Kill a Mockingbird",
      "1984",
      "The Great Gatsby",
      "The Catcher in the Rye",
      "The Hobbit",
      "The Chronicles of Narnia",
      "Jane Eyre",
      "Wuthering Heights",
      "Little Women",
      "The Hunger Games",
      "The Da Vinci Code",
      "The Alchemist",
      "Brave New World",
      "The Odyssey",
      "Don Quixote",
      "Moby Dick",
      "Alice in Wonderland",
      "Dracula",
      "Frankenstein",
      "The Picture of Dorian Gray",
      "The Adventures of Sherlock Holmes",
      "The Count of Monte Cristo",
      "Les Misérables",
      "War and Peace",
      "Crime and Punishment",
      "One Hundred Years of Solitude",
      "The Little Prince",
      "The Grapes of Wrath",
      "The Color Purple",
      "The Handmaid's Tale",
      "The Road",
      "Life of Pi",
      "The Book Thief",
      "The Kite Runner",
      "Gone with the Wind",
      "The Secret Garden",
      "Charlotte's Web",
    ],
  },
};

export const ALL_CATEGORIES = [
  {
    id: "misc",
    name: "🎲 All Categories",
    prompt: "mixed variety of charades-friendly topics",
  },
  {
    id: "movies",
    name: "🎬 TV Shows & Movies",
    prompt: "popular TV shows and movies",
  },
  {
    id: "disney",
    name: "🏰 Disney Characters",
    prompt: "Disney and Pixar characters",
  },
  {
    id: "superheroes",
    name: "🦸‍♂️ Superheroes",
    prompt: "popular superheroes (especially Marvel)",
  },
  {
    id: "celebrities",
    name: "⭐ Celebrities",
    prompt: "famous celebrities",
  },
  {
    id: "animals",
    name: "🦁 Animals",
    prompt: "animals",
  },
  {
    id: "food",
    name: "🍕 Food",
    prompt: "ingredients and dishes",
  },
  {
    id: "songs",
    name: "🎵 Pop Songs",
    prompt: "popular songs",
  },
  {
    id: "accents",
    name: "🗣️ Accents & Impressions",
    prompt: "accents and character impressions",
  },
  {
    id: "historical",
    name: "👑 Historical Figures",
    prompt: "famous historical figures",
  },
  {
    id: "geography",
    name: "🌎 Geography",
    prompt: "U.S. States, Cities, and Countries",
  },
  {
    id: "books",
    name: "📚 Books",
    prompt: "book titles",
  },
  {
    id: "custom",
    name: "🎯 Custom",
    prompt: "",
  },
] as const;

export const getRandomOptionsForCategory = (
  categoryId: string,
  count: number
): string[] => {
  if (categoryId === "misc") {
    // For misc, get random options from all categories
    const allOptions = Object.values(CATEGORY_OPTIONS).flatMap(
      (cat) => cat.options
    );
    return shuffleArray([...allOptions]).slice(0, count);
  }

  if (categoryId === "custom") {
    return [];
  }

  const categoryOptions = CATEGORY_OPTIONS[categoryId]?.options || [];
  return shuffleArray([...categoryOptions]).slice(0, count);
};

const shuffleArray = <T>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};
