interface Category {
  id: string;
  name: string;
  prompt: string;
  options?: string[];
}

export const CATEGORIES: Category[] = [
  {
    id: "misc",
    name: "🎲 All Categories",
    prompt: "mixed variety of charades-friendly topics",
  },
  {
    id: "movies",
    name: "🎬 TV Shows & Movies",
    prompt: "popular TV shows and movies",
    options: [
      "Breaking Bad",
      "The Office",
      "Friends",
      "Stranger Things",
      "Game of Thrones",
      "Star Wars",
      "Harry Potter",
      "The Matrix",
      "Jurassic Park",
      "The Lion King",
      "Titanic",
      "Avatar",
      "The Avengers",
      "Lord of the Rings",
      "Finding Nemo",
      "The Simpsons",
      "Seinfeld",
      "The Walking Dead",
      "Black Mirror",
      "Squid Game",
      "Inception",
      "Forrest Gump",
      "The Godfather",
      "Pulp Fiction",
      "Fight Club",
      "The Dark Knight",
      "Jaws",
      "E.T.",
      "Back to the Future",
      "Indiana Jones",
      "The Shawshank Redemption",
      "The Wizard of Oz",
      "Ghostbusters",
      "The Terminator",
      "Toy Story",
      "The Silence of the Lambs",
      "Gladiator",
      "The Big Bang Theory",
      "How I Met Your Mother",
      "Modern Family",
      "The Crown",
      "Bridgerton",
      "The Mandalorian",
      "The Last of Us",
      "Wednesday",
      "The Boys",
      "Better Call Saul",
      "Dexter",
      "Lost",
      "The Wire",
      "Mad Men",
      "The Sopranos",
      "Frasier",
      "Cheers",
      "The X-Files",
      "Twin Peaks",
      "The Twilight Zone",
      "The Good Place",
      "Parks and Recreation",
      "Brooklyn Nine-Nine",
      "The Office UK",
      "Downton Abbey",
      "Westworld",
      "True Detective",
      "Chernobyl",
      "Band of Brothers",
      "The Pacific",
      "Planet Earth",
      "Blue Planet",
      "Cosmos",
      "The Witcher",
      "House of the Dragon",
      "Succession",
      "Ted Lasso",
      "Abbott Elementary",
      "Schitt's Creek",
      "The Bear",
      "Fleabag",
      "Killing Eve",
      "Ozark",
      "Narcos",
      "Money Heist",
      "Dark",
      "The Umbrella Academy",
      "Daredevil",
      "Jessica Jones",
      "WandaVision",
      "Loki",
      "Moon Knight",
      "Ms. Marvel",
      "Andor",
      "House of Cards",
      "The Americans",
      "Homeland",
      "24",
      "Prison Break",
      "Grey's Anatomy",
      "ER",
      "House",
      "The Good Doctor",
      "This Is Us",
      "The Handmaid's Tale",
      "Black Books",
      "Father Ted",
      "The IT Crowd",
      "Peep Show",
      "Only Murders in the Building",
      "The White Lotus",
      "Yellowjackets",
      "Severance",
      "The Morning Show",
    ],
  },
  {
    id: "disney",
    name: "🏰 Disney Characters",
    prompt: "Disney and Pixar characters",
    options: [
      "Mickey Mouse",
      "Donald Duck",
      "Goofy",
      "Minnie Mouse",
      "Pluto",
      "Snow White",
      "Cinderella",
      "Ariel",
      "Belle",
      "Jasmine",
      "Aladdin",
      "Simba",
      "Timon",
      "Pumbaa",
      "Woody",
      "Buzz Lightyear",
      "Nemo",
      "Dory",
      "Elsa",
      "Anna",
      "Olaf",
      "Moana",
      "Maui",
      "Mulan",
      "Mushu",
      "Peter Pan",
      "Captain Hook",
      "Tinker Bell",
      "Winnie the Pooh",
      "Tigger",
      "Piglet",
      "Eeyore",
      "Rabbit",
      "Roo",
      "Kanga",
      "Bambi",
      "Thumper",
      "Dumbo",
      "Timothy Mouse",
      "Pinocchio",
      "Jiminy Cricket",
      "Geppetto",
      "Mowgli",
      "Baloo",
      "Bagheera",
      "King Louie",
      "Shere Khan",
      "Robin Hood",
      "Little John",
      "Maid Marian",
      "Merida",
      "Rapunzel",
      "Flynn Rider",
      "Pascal",
      "Maximus",
      "Hercules",
      "Meg",
      "Phil",
      "Zeus",
      "Hades",
      "Pocahontas",
      "John Smith",
      "Meeko",
      "Flit",
      "Governor Ratcliffe",
      "Tarzan",
      "Jane",
      "Terk",
      "Tantor",
      "Clayton",
      "Lilo",
      "Stitch",
      "Nani",
      "Pleakley",
      "Jumba",
      "Remy",
      "Linguini",
      "Colette",
      "Anton Ego",
      "Emile",
      "WALL-E",
      "EVE",
      "M-O",
      "AUTO",
      "Captain B. McCrea",
      "Carl Fredricksen",
      "Russell",
      "Dug",
      "Kevin",
      "Charles Muntz",
      "Judy Hopps",
      "Nick Wilde",
      "Flash",
      "Chief Bogo",
      "Bellwether",
      "Hiro Hamada",
      "Baymax",
      "GoGo",
      "Honey Lemon",
      "Fred",
      "Miguel",
      "Héctor",
      "Mama Coco",
      "Dante",
      "Ernesto de la Cruz",
      "Joy",
      "Sadness",
      "Anger",
      "Fear",
      "Disgust",
      "Bing Bong",
      "Riley",
      "Ian Lightfoot",
      "Barley Lightfoot",
      "The Manticore",
    ],
  },
  {
    id: "superheroes",
    name: "🦸‍♂️ Superheroes",
    prompt: "popular superheroes (especially Marvel)",
    options: [
      "Spider-Man",
      "Batman",
      "Superman",
      "Wonder Woman",
      "Iron Man",
      "Captain America",
      "Thor",
      "Hulk",
      "Black Widow",
      "Black Panther",
      "Doctor Strange",
      "Wolverine",
      "Deadpool",
      "Flash",
      "Green Lantern",
      "Aquaman",
      "Ant-Man",
      "Captain Marvel",
      "Hawkeye",
      "Vision",
      "Scarlet Witch",
      "Loki",
      "Thanos",
      "Star-Lord",
      "Groot",
      "Rocket Raccoon",
      "Professor X",
      "Magneto",
      "Storm",
      "Jean Grey",
      "Cyclops",
      "Beast",
      "Rogue",
      "Gambit",
      "Nightcrawler",
      "Daredevil",
      "Punisher",
      "Ghost Rider",
      "Blade",
      "Moon Knight",
      "She-Hulk",
      "Ms. Marvel",
      "Miles Morales",
      "Spider-Gwen",
      "Venom",
      "Carnage",
      "Doctor Doom",
      "Green Goblin",
      "Joker",
      "Harley Quinn",
      "Catwoman",
      "Penguin",
      "Riddler",
      "Two-Face",
      "Poison Ivy",
      "Lex Luthor",
      "Brainiac",
      "General Zod",
      "Darkseid",
      "Doomsday",
      "Red Skull",
      "Winter Soldier",
      "Ultron",
      "Hela",
      "Killmonger",
      "Doctor Octopus",
      "Sandman",
      "Mysterio",
      "Vulture",
      "Electro",
      "Phoenix",
      "Apocalypse",
      "Juggernaut",
      "Sabretooth",
      "Mystique",
      "Black Adam",
      "Shazam",
      "Constantine",
      "Batgirl",
      "Supergirl",
      "Robin",
      "Nightwing",
      "Red Hood",
      "Batwoman",
      "Oracle",
      "Nick Fury",
      "Maria Hill",
      "Phil Coulson",
      "Jessica Jones",
      "Luke Cage",
      "Iron Fist",
      "Black Bolt",
      "Medusa",
      "Crystal",
      "Karnak",
      "Blue Beetle",
      "Booster Gold",
      "Zatanna",
      "Black Canary",
      "Green Arrow",
      "Martian Manhunter",
      "Cyborg",
      "Beast Boy",
      "Starfire",
      "Raven",
      "Kid Flash",
      "Superboy",
      "Wonder Girl",
      "Aqualad",
      "Speedy",
    ],
  },
  {
    id: "celebrities",
    name: "⭐ Celebrities",
    prompt: "famous celebrities",
    options: [
      "Tom Hanks",
      "Morgan Freeman",
      "Leonardo DiCaprio",
      "Brad Pitt",
      "Jennifer Lawrence",
      "Meryl Streep",
      "Will Smith",
      "Johnny Depp",
      "Taylor Swift",
      "Beyoncé",
      "Lady Gaga",
      "Justin Bieber",
      "Drake",
      "Adele",
      "Ed Sheeran",
      "Rihanna",
      "Barack Obama",
      "Donald Trump",
      "Elon Musk",
      "Bill Gates",
      "Mark Zuckerberg",
      "Oprah Winfrey",
      "Ellen DeGeneres",
      "Jimmy Fallon",
      "Gordon Ramsay",
      "David Beckham",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Michael Jordan",
      "LeBron James",
      "Serena Williams",
      "Michael Phelps",
      "Albert Einstein",
      "Stephen Hawking",
      "Pablo Picasso",
      "Vincent van Gogh",
      "Madonna",
      "Michael Jackson",
      "Elvis Presley",
      "Bob Marley",
      "Ariana Grande",
      "Bruno Mars",
      "Katy Perry",
      "Eminem",
      "Kanye West",
      "Kim Kardashian",
      "Jennifer Aniston",
      "Robert Downey Jr",
      "Chris Hemsworth",
      "Scarlett Johansson",
      "Dwayne Johnson",
      "Ryan Reynolds",
      "Emma Watson",
      "Daniel Radcliffe",
      "Justin Timberlake",
      "Britney Spears",
      "Selena Gomez",
      "Miley Cyrus",
      "Zendaya",
      "Tom Holland",
      "Billie Eilish",
      "Post Malone",
      "Cardi B",
      "Kendrick Lamar",
      "Harry Styles",
      "Chris Pratt",
      "Margot Robbie",
      "Gal Gadot",
      "Keanu Reeves",
      "Tom Cruise",
      "Julia Roberts",
      "Sandra Bullock",
      "Nicole Kidman",
      "Hugh Jackman",
      "Russell Crowe",
      "Angelina Jolie",
      "George Clooney",
      "Matt Damon",
      "Ben Affleck",
      "Jennifer Lopez",
      "Shakira",
      "Justin Trudeau",
      "Queen Elizabeth II",
      "Prince William",
      "Kate Middleton",
      "Prince Harry",
      "Meghan Markle",
      "David Attenborough",
      "Michelle Obama",
      "Joe Biden",
      "Kamala Harris",
      "Alexandria Ocasio-Cortez",
      "Bernie Sanders",
      "Arnold Schwarzenegger",
      "Jackie Chan",
      "Bruce Lee",
      "Morgan Freeman",
      "Samuel L. Jackson",
      "Denzel Washington",
      "Will Ferrell",
      "Jim Carrey",
      "Steve Carell",
      "Adam Sandler",
      "Eddie Murphy",
      "Robin Williams",
      "Bill Murray",
      "Tom Brady",
      "Roger Federer",
      "Usain Bolt",
      "Tiger Woods",
      "David Copperfield",
      "Penn & Teller",
      "Stephen King",
      "J.K. Rowling",
      "George R.R. Martin",
      "Christopher Nolan",
      "Steven Spielberg",
      "Martin Scorsese",
      "Quentin Tarantino",
      "James Cameron",
      "Stan Lee",
      "Walt Disney",
      "Steve Jobs",
      "Jeff Bezos",
      "Warren Buffett",
      "Richard Branson",
      "Jack Ma",
      "David Bowie",
      "Prince",
      "Freddie Mercury",
      "Paul McCartney",
      "Mick Jagger",
      "Elton John",
      "Stevie Wonder",
      "Ray Charles",
      "Frank Sinatra",
    ],
  },
  {
    id: "animals",
    name: "🦁 Animals",
    prompt: "animals",
    options: [
      "Lion",
      "Elephant",
      "Giraffe",
      "Monkey",
      "Penguin",
      "Kangaroo",
      "Koala",
      "Panda",
      "Tiger",
      "Bear",
      "Wolf",
      "Fox",
      "Deer",
      "Zebra",
      "Hippopotamus",
      "Rhinoceros",
      "Crocodile",
      "Snake",
      "Eagle",
      "Owl",
      "Parrot",
      "Flamingo",
      "Octopus",
      "Dolphin",
      "Shark",
      "Whale",
      "Butterfly",
      "Spider",
      "Ant",
      "Bee",
      "Sloth",
      "Platypus",
      "Peacock",
      "Ostrich",
      "Gorilla",
      "Cheetah",
      "Camel",
      "Seal",
      "Polar Bear",
      "Penguin",
      "Hamster",
      "Guinea Pig",
      "Rabbit",
      "Cat",
      "Dog",
      "Horse",
      "Cow",
      "Pig",
      "Sheep",
      "Goat",
      "Chicken",
      "Rooster",
      "Duck",
      "Goose",
      "Turkey",
      "Pigeon",
      "Seagull",
      "Crow",
      "Raven",
      "Blue Jay",
      "Cardinal",
      "Hummingbird",
      "Woodpecker",
      "Pelican",
      "Swan",
      "Toucan",
      "Macaw",
      "Cockatoo",
      "Iguana",
      "Chameleon",
      "Gecko",
      "Turtle",
      "Tortoise",
      "Frog",
      "Toad",
      "Salamander",
      "Newt",
      "Fish",
      "Goldfish",
      "Clownfish",
      "Seahorse",
      "Starfish",
      "Jellyfish",
      "Crab",
      "Lobster",
      "Shrimp",
      "Squid",
      "Snail",
      "Slug",
      "Ladybug",
      "Praying Mantis",
      "Grasshopper",
      "Cricket",
      "Caterpillar",
      "Dragonfly",
      "Mosquito",
      "Fly",
      "Wasp",
      "Hornet",
      "Scorpion",
      "Tarantula",
      "Centipede",
      "Millipede",
      "Raccoon",
      "Skunk",
      "Squirrel",
      "Chipmunk",
      "Beaver",
      "Otter",
      "Badger",
      "Hedgehog",
      "Armadillo",
      "Opossum",
      "Mole",
      "Bat",
      "Lemur",
      "Meerkat",
      "Wombat",
      "Tapir",
      "Pangolin",
      "Anteater",
      "Capybara",
      "Alpaca",
      "Llama",
      "Yak",
      "Bison",
      "Moose",
      "Elk",
      "Reindeer",
      "Gazelle",
      "Antelope",
      "Wildebeest",
      "Warthog",
      "Hyena",
      "Jackal",
      "Dingo",
      "Coyote",
      "Lynx",
      "Bobcat",
      "Panther",
      "Jaguar",
      "Leopard",
      "Mountain Lion",
      "Puma",
      "Red Panda",
      "Sun Bear",
      "Grizzly Bear",
      "Black Bear",
      "Walrus",
      "Sea Lion",
      "Manatee",
      "Dugong",
      "Narwhal",
      "Beluga Whale",
      "Orca",
      "Porpoise",
      "Hammerhead Shark",
      "Great White Shark",
      "Manta Ray",
      "Stingray",
      "Swordfish",
      "Marlin",
      "Tuna",
      "Salmon",
      "Barracuda",
      "Piranha",
      "Eel",
      "Lionfish",
      "Pufferfish",
      "Anglerfish",
      "Axolotl",
      "Komodo Dragon",
      "Anaconda",
      "Python",
      "Cobra",
      "Viper",
      "Rattlesnake",
      "Boa Constrictor",
      "Monitor Lizard",
      "Bearded Dragon",
      "Vulture",
      "Falcon",
      "Hawk",
      "Osprey",
      "Albatross",
      "Crane",
      "Stork",
      "Ibis",
      "Kingfisher",
      "Quail",
      "Pheasant",
      "Kookaburra",
      "Hornbill",
      "Cassowary",
      "Kiwi",
      "Dodo",
      "Mandrill",
      "Baboon",
      "Orangutan",
      "Chimpanzee",
      "Bonobo",
      "Gibbon",
      "Marmoset",
      "Tamarin",
      "Tarsier",
      "Proboscis Monkey",
      "Howler Monkey",
      "Spider Monkey",
      "Capuchin Monkey",
    ],
  },
  {
    id: "birds",
    name: "🐦 Bird Species",
    prompt: "birds",
    options: [
      "American Robin",
      "Northern Cardinal",
      "Blue Jay",
      "Black-capped Chickadee",
      "American Goldfinch",
      "House Sparrow",
      "Downy Woodpecker",
      "Red-winged Blackbird",
      "European Starling",
      "House Finch",
      "Northern Mockingbird",
      "Tufted Titmouse",
      "White-breasted Nuthatch",
      "American Crow",
      "Barn Swallow",
      "Cedar Waxwing",
      "Mourning Dove",
      "Dark-eyed Junco",
      "Song Sparrow",
      "Carolina Wren",
      "Purple Finch",
      "Common Grackle",
      "Tree Swallow",
      "Red-bellied Woodpecker",
      "Red-tailed Hawk",
      "Great Blue Heron",
      "Pileated Woodpecker",
      "Belted Kingfisher",
      "Eastern Bluebird",
      "Baltimore Oriole",
      "Ruby-throated Hummingbird",
      "Yellow Warbler",
      "Great Horned Owl",
      "Wood Duck",
      "Mallard",
      "Canada Goose",
      "Turkey Vulture",
      "Barred Owl",
      "American Kestrel",
      "Peregrine Falcon",
      "Bald Eagle",
      "Sandhill Crane",
      "Common Loon",
      "Green Heron",
      "Wild Turkey",
      "Black-billed Magpie",
      "Common Raven",
      "Snow Bunting",
      "Rock Pigeon",
      "Northern Flicker",
      "Ring-billed Gull",
      "Herring Gull",
      "Killdeer",
    ],
  },
  {
    id: "careers",
    name: "💼 Careers",
    prompt: "careers",
    options: [
      "Doctor",
      "Lawyer",
      "Teacher",
      "Engineer",
      "Artist",
      "Writer",
      "Nurse",
      "Software Developer",
      "Accountant",
      "Chef",
      "Police Officer",
      "Firefighter",
      "Architect",
      "Dentist",
      "Veterinarian",
      "Pharmacist",
      "Psychologist",
      "Physical Therapist",
      "Electrician",
      "Plumber",
      "Carpenter",
      "Mechanic",
      "Pilot",
      "Flight Attendant",
      "Real Estate Agent",
      "Financial Advisor",
      "Marketing Manager",
      "Graphic Designer",
      "Web Designer",
      "Interior Designer",
      "Fashion Designer",
      "Photographer",
      "Journalist",
      "Editor",
      "Publisher",
      "Librarian",
      "Professor",
      "Principal",
      "School Counselor",
      "Social Worker",
      "Therapist",
      "Personal Trainer",
      "Nutritionist",
      "Dietitian",
      "Chiropractor",
      "Optometrist",
      "Speech Pathologist",
      "Occupational Therapist",
      "Paramedic",
      "EMT",
      "Surgeon",
      "Anesthesiologist",
      "Pediatrician",
      "Dermatologist",
      "Cardiologist",
      "Neurologist",
      "Oncologist",
      "Radiologist",
      "Psychiatrist",
      "Orthodontist",
      "Dental Hygienist",
      "Nurse Practitioner",
      "Physician Assistant",
      "Medical Laboratory Technician",
      "Pharmacy Technician",
      "Massage Therapist",
      "Yoga Instructor",
      "Fitness Instructor",
      "Athletic Trainer",
      "Sports Coach",
      "Professional Athlete",
      "Referee",
      "Music Teacher",
      "Dance Instructor",
      "Actor",
      "Musician",
      "Singer",
      "Dancer",
      "Choreographer",
      "Film Director",
      "Producer",
      "Screenwriter",
      "Animator",
      "Game Developer",
      "UX Designer",
      "Data Scientist",
      "Systems Analyst",
      "Network Administrator",
      "Cybersecurity Analyst",
      "Database Administrator",
      "IT Support Specialist",
      "Quality Assurance Tester",
      "Project Manager",
      "Product Manager",
      "Business Analyst",
      "Management Consultant",
      "Human Resources Manager",
      "Recruiter",
      "Training Coordinator",
      "Operations Manager",
      "Supply Chain Manager",
      "Logistics Coordinator",
      "Warehouse Manager",
      "Retail Manager",
      "Sales Representative",
      "Insurance Agent",
      "Investment Banker",
      "Stock Broker",
      "Economist",
      "Statistician",
      "Mathematician",
      "Research Scientist",
      "Biologist",
      "Chemist",
      "Physicist",
      "Environmental Scientist",
      "Geologist",
      "Meteorologist",
      "Astronomer",
      "Marine Biologist",
      "Zoologist",
      "Botanist",
      "Agricultural Scientist",
      "Food Scientist",
      "Forensic Scientist",
      "Archaeological Scientist",
      "Anthropologist",
      "Historian",
      "Political Scientist",
      "Sociologist",
      "Urban Planner",
      "Landscape Architect",
      "Civil Engineer",
      "Mechanical Engineer",
      "Electrical Engineer",
      "Chemical Engineer",
      "Aerospace Engineer",
      "Biomedical Engineer",
      "Environmental Engineer",
      "Industrial Engineer",
      "Materials Engineer",
      "Mining Engineer",
      "Nuclear Engineer",
      "Petroleum Engineer",
      "Robotics Engineer",
      "Sound Engineer",
      "Surveyor",
      "Construction Manager",
      "Building Inspector",
      "HVAC Technician",
      "Welder",
      "Machinist",
      "Tool and Die Maker",
      "Auto Body Repair Technician",
      "Diesel Mechanic",
      "Aircraft Mechanic",
      "Boat Mechanic",
      "Bicycle Repair Technician",
      "Locksmith",
      "Glazier",
      "Roofer",
      "Painter",
      "Plasterer",
      "Stonemason",
      "Tile Setter",
      "Carpet Installer",
      "Cabinet Maker",
      "Furniture Maker",
      "Upholsterer",
      "Tailor",
      "Seamstress",
      "Jeweler",
      "Watch Maker",
      "Glass Blower",
      "Potter",
      "Sculptor",
      "Printmaker",
      "Illustrator",
      "Art Restorer",
      "Museum Curator",
      "Gallery Owner",
      "Art Dealer",
      "Auctioneer",
      "Travel Agent",
      "Tour Guide",
      "Hotel Manager",
      "Restaurant Manager",
      "Event Planner",
      "Wedding Planner",
      "Florist",
      "Baker",
      "Butcher",
      "Barista",
      "Bartender",
      "Sommelier",
      "Food Critic",
      "Food Stylist",
      "Personal Chef",
      "Caterer",
      "Pest Control Technician",
      "Landscaper",
      "Gardener",
      "Arborist",
      "Farmer",
      "Rancher",
      "Fisherman",
      "Logger",
      "Park Ranger",
      "Zookeeper",
      "Animal Trainer",
      "Dog Groomer",
      "Pet Sitter",
      "Veterinary Technician",
      "Wildlife Rehabilitator",
      "Taxidermist",
      "Mortician",
      "Funeral Director",
      "Court Reporter",
      "Paralegal",
      "Judge",
      "Mediator",
      "Notary Public",
      "Patent Attorney",
      "Tax Attorney",
      "Immigration Lawyer",
      "Corporate Lawyer",
      "Criminal Defense Attorney",
    ],
  },
  {
    id: "instruments",
    name: "🎸 Instruments",
    prompt: "instruments",
    options: [
      "Piano",
      "Guitar",
      "Drums",
      "Bass",
      "Saxophone",
      "Violin",
      "Cello",
      "Trumpet",
      "Flute",
      "Clarinet",
      "Trombone",
      "French Horn",
      "Tuba",
      "Oboe",
      "Bassoon",
      "Harp",
      "Viola",
      "Double Bass",
      "Banjo",
      "Mandolin",
      "Ukulele",
      "Accordion",
      "Harmonica",
      "Bagpipes",
      "Xylophone",
      "Marimba",
      "Vibraphone",
      "Timpani",
      "Cymbals",
      "Triangle",
      "Tambourine",
      "Bongos",
      "Congas",
      "Didgeridoo",
      "Pan Flute",
      "Ocarina",
      "Synthesizer",
      "Electric Guitar",
      "Bass Guitar",
      "Keytar",
      "Steel Drums",
      "Kalimba",
      "Dulcimer",
      "Lute",
    ],
  },
  {
    id: "medieval items",
    name: "🏰 Medieval Items",
    prompt: "medieval items",
    options: [
      "Sword",
      "Shield",
      "Helmet",
      "Armor",
      "Bow",
      "Arrow",
      "Lance",
      "Mace",
      "Flail",
      "Dagger",
      "Crossbow",
      "Spear",
      "Battle Axe",
      "Halberd",
      "Chainmail",
      "Plate Armor",
      "Gauntlets",
      "Greaves",
      "Pauldrons",
      "Breastplate",
      "Crown",
      "Scepter",
      "Throne",
      "Goblet",
      "Chalice",
      "Tapestry",
      "Banner",
      "Coat of Arms",
      "Torch",
      "Candelabra",
      "Hourglass",
      "Sundial",
      "Quill",
      "Scroll",
      "Parchment",
      "Inkwell",
      "Wax Seal",
      "Cauldron",
      "Spinning Wheel",
      "Loom",
      "Anvil",
      "Forge",
      "Bellows",
      "Horseshoe",
      "Saddle",
      "Bridle",
      "Cart",
      "Wagon",
      "Catapult",
      "Trebuchet",
      "Battering Ram",
      "Portcullis",
      "Drawbridge",
      "Castle Gate",
      "Tower Shield",
      "War Horn",
    ],
  },
  {
    id: "food",
    name: "🍕 Food",
    prompt: "ingredients and dishes",
    options: [
      "Pizza",
      "Hamburger",
      "Sushi",
      "Spaghetti",
      "Taco",
      "Ice Cream",
      "Chocolate Cake",
      "French Fries",
      "Hot Dog",
      "Pancakes",
      "Waffles",
      "Donut",
      "Cookie",
      "Sandwich",
      "Salad",
      "Soup",
      "Steak",
      "Chicken Wings",
      "Burrito",
      "Nachos",
      "Popcorn",
      "Apple Pie",
      "Cupcake",
      "Croissant",
      "Ramen",
      "Fried Rice",
      "Curry",
      "Lasagna",
      "Mac and Cheese",
      "Grilled Cheese",
      "Peanut Butter & Jelly",
      "Cereal",
      "Oatmeal",
      "Yogurt",
      "Banana Split",
      "Milkshake",
      "Smoothie",
      "Orange Juice",
      "Coffee",
      "Tea",
      "Lemonade",
      "Soda",
      "Water",
      "Beer",
      "Wine",
      "Cocktail",
      "Martini",
      "Margarita",
      "Mojito",
      "Bloody Mary",
      "Chicken Noodle Soup",
      "Tomato Soup",
      "French Onion Soup",
      "Clam Chowder",
      "Minestrone",
      "Caesar Salad",
      "Greek Salad",
      "Cobb Salad",
      "Potato Salad",
      "Coleslaw",
      "Mashed Potatoes",
      "Baked Potato",
      "Sweet Potato Fries",
      "Onion Rings",
      "Chicken Nuggets",
      "Fish and Chips",
      "Shrimp Cocktail",
      "Lobster Roll",
      "Crab Cake",
      "Salmon",
      "Tuna",
      "Swordfish",
      "Cod",
      "Halibut",
      "Tilapia",
      "Beef Stew",
      "Chili",
      "Gumbo",
      "Jambalaya",
      "Paella",
      "Pad Thai",
      "Spring Roll",
      "Egg Roll",
      "Dumpling",
      "Dim Sum",
      "Fried Chicken",
      "Roast Chicken",
      "Turkey",
      "Ham",
      "Bacon",
      "Eggs Benedict",
      "Omelet",
      "Scrambled Eggs",
      "Sunny Side Up",
      "Hard Boiled Egg",
      "Toast",
      "Bagel",
      "English Muffin",
      "Biscuit",
      "Cornbread",
      "Brownie",
      "Chocolate Chip Cookie",
      "Sugar Cookie",
      "Oatmeal Raisin Cookie",
      "Snickerdoodle",
      "Cheesecake",
      "Tiramisu",
      "Crème Brûlée",
      "Pudding",
      "Jell-O",
      "Falafel",
      "Hummus",
      "Pita Bread",
      "Tzatziki",
      "Gyro",
      "Shawarma",
      "Kebab",
      "Biryani",
      "Butter Chicken",
      "Naan",
      "Samosa",
      "Tandoori Chicken",
      "Sushi Roll",
      "Sashimi",
      "Tempura",
      "Udon",
      "Miso Soup",
      "Pho",
      "Banh Mi",
      "Spring Roll",
      "Summer Roll",
      "Pad See Ew",
      "Green Curry",
      "Red Curry",
      "Tom Yum Soup",
      "Satay",
      "Fried Rice",
      "Lo Mein",
      "Chow Mein",
      "Kung Pao Chicken",
      "Sweet and Sour Pork",
      "Mapo Tofu",
      "Hot Pot",
      "Peking Duck",
      "Xiaolongbao",
      "Scallion Pancake",
      "Beef and Broccoli",
      "Carbonara",
      "Alfredo",
      "Pesto Pasta",
      "Gnocchi",
      "Risotto",
      "Osso Buco",
      "Bruschetta",
      "Caprese Salad",
      "Margherita Pizza",
      "Calzone",
      "Stromboli",
      "Focaccia",
      "Ciabatta",
      "Baguette",
      "Sourdough",
      "Rye Bread",
      "Challah",
      "Brioche",
      "Croissant",
      "Pain au Chocolat",
      "Danish Pastry",
      "Éclair",
      "Macaron",
      "Crêpe",
      "Quiche",
      "Ratatouille",
      "Coq au Vin",
      "Beef Bourguignon",
      "French Onion Soup",
      "Bouillabaisse",
      "Escargot",
      "Foie Gras",
      "Croque Monsieur",
      "Croque Madame",
      "Moules Frites",
      "Steak Frites",
      "Beef Wellington",
      "Shepherd's Pie",
      "Fish and Chips",
      "Bangers and Mash",
      "Yorkshire Pudding",
      "Cottage Pie",
      "Toad in the Hole",
      "Full English Breakfast",
      "Scotch Egg",
      "Black Pudding",
      "Haggis",
      "Cornish Pasty",
      "Beef Stroganoff",
      "Pierogi",
      "Schnitzel",
      "Bratwurst",
      "Sauerkraut",
      "Spätzle",
      "Currywurst",
      "Döner Kebab",
      "Paella",
      "Gazpacho",
      "Tortilla Española",
      "Patatas Bravas",
      "Churros",
      "Empanada",
      "Ceviche",
      "Tamales",
      "Enchiladas",
      "Chilaquiles",
      "Mole",
      "Pozole",
      "Elote",
      "Guacamole",
      "Pico de Gallo",
      "Fajitas",
      "Quesadilla",
      "Chimichanga",
      "Tostada",
      "Arepa",
      "Pão de Queijo",
      "Açaí Bowl",
      "Poutine",
      "Maple Syrup",
    ],
  },
  {
    id: "sweets",
    name: "🍬 Sweets",
    prompt: "candy and desserts",
    options: [
      "M&M's",
      "Snickers",
      "Twix",
      "Kit Kat",
      "Reese's Peanut Butter Cups",
      "Skittles",
      "Starburst",
      "Hershey's Kisses",
      "Milky Way",
      "3 Musketeers",
      "Butterfinger",
      "Twizzlers",
      "Sour Patch Kids",
      "Swedish Fish",
      "Gummy Bears",
      "Jelly Beans",
      "Nerds",
      "Smarties",
      "Tootsie Roll",
      "Tootsie Pop",
      "Dum Dums",
      "Life Savers",
      "Jolly Ranchers",
      "Warheads",
      "Air Heads",
      "Now and Later",
      "Mike and Ike",
      "Hot Tamales",
      "Red Hots",
      "Milk Duds",
      "Whoppers",
      "Junior Mints",
      "York Peppermint Pattie",
      "Almond Joy",
      "Mounds",
      "PayDay",
      "Baby Ruth",
      "100 Grand Bar",
      "Crunch Bar",
      "Toblerone",
      "Ferrero Rocher",
      "Lindt Truffles",
      "Ghirardelli Squares",
      "Godiva Chocolates",
      "Rolo",
      "Heath Bar",
      "Skor",
      "Take 5",
      "Charleston Chew",
      "Chocolate Chip Cookies",
      "Oreos",
      "Chips Ahoy",
      "Nutter Butters",
      "Fig Newtons",
      "Girl Scout Thin Mints",
      "Samoas",
      "Tagalongs",
      "Do-si-dos",
      "Trefoils",
      "Milano Cookies",
      "Pepperidge Farm Cookies",
      "Famous Amos",
      "Pecan Sandies",
      "Shortbread Cookies",
      "Macarons",
      "Biscotti",
      "Madeleines",
      "Churros",
      "Funnel Cake",
      "Cotton Candy",
      "Caramel Corn",
      "Kettle Corn",
      "Rice Krispies Treats",
      "Pop-Tarts",
      "Toaster Strudel",
      "Hostess Cupcakes",
      "Twinkies",
      "Ding Dongs",
      "Ho Hos",
      "Sno Balls",
      "Little Debbie Snacks",
      "Cosmic Brownies",
      "Oatmeal Cream Pies",
      "Swiss Rolls",
      "Zebra Cakes",
      "Star Crunch",
      "Nutty Bars",
      "Honey Buns",
      "Cinnamon Rolls",
      "Danish Pastries",
      "Croissants",
      "Eclairs",
      "Cream Puffs",
      "Profiteroles",
      "Cannoli",
      "Tiramisu",
      "Cheesecake",
      "New York Cheesecake",
      "Chocolate Cake",
      "Red Velvet Cake",
      "Carrot Cake",
      "Angel Food Cake",
      "Devil's Food Cake",
      "Pound Cake",
      "Bundt Cake",
      "Layer Cake",
      "Sheet Cake",
      "Cupcakes",
      "Brownies",
      "Blondies",
      "Lemon Bars",
      "Apple Pie",
      "Cherry Pie",
      "Peach Pie",
      "Blueberry Pie",
      "Pumpkin Pie",
      "Pecan Pie",
      "Key Lime Pie",
      "Banana Cream Pie",
      "Coconut Cream Pie",
      "Chocolate Cream Pie",
      "French Silk Pie",
      "Lemon Meringue Pie",
      "Custard",
      "Pudding",
      "Rice Pudding",
      "Bread Pudding",
      "Crème Brûlée",
      "Flan",
      "Panna Cotta",
      "Mousse",
      "Soufflé",
      "Gelato",
      "Ice Cream",
      "Frozen Yogurt",
      "Sorbet",
      "Sherbet",
      "Ice Cream Sandwich",
      "Ice Cream Cone",
      "Sundae",
      "Banana Split",
      "Root Beer Float",
      "Milkshake",
      "Smoothie",
      "Slushie",
      "Snow Cone",
      "Italian Ice",
      "Popsicle",
      "Fudgesicle",
      "Creamsicle",
      "Klondike Bar",
      "Drumstick",
      "Choco Taco",
      "Ben & Jerry's",
      "Häagen-Dazs",
      "Baskin-Robbins",
      "Dairy Queen",
      "Cold Stone Creamery",
      "Dippin' Dots",
      "Frozen Custard",
      "Soft Serve",
      "Frozen Yogurt",
      "Froyo Toppings",
      "Sprinkles",
      "Jimmies",
      "Rainbow Sprinkles",
      "Chocolate Chips",
      "Mini M&M's",
      "Crushed Oreos",
      "Graham Crackers",
      "Marshmallows",
      "Hot Fudge",
      "Caramel Sauce",
      "Strawberry Sauce",
      "Whipped Cream",
      "Maraschino Cherries",
      "Nuts",
      "Candy Corn",
      "Peeps",
      "Conversation Hearts",
      "Candy Canes",
      "Rock Candy",
      "Lollipops",
      "Taffy",
      "Licorice",
      "Fruit Roll-Ups",
      "Gushers",
      "Fruit by the Foot",
      "Ring Pops",
      "Push Pops",
      "Fun Dip",
      "Pixie Sticks",
      "Pop Rocks",
      "Bubble Gum",
      "Bazooka Joe",
      "Double Bubble",
      "Big League Chew",
      "Hubba Bubba",
      "Mentos",
      "Tic Tacs",
      "Altoids",
      "Life Savers Mints",
      "Ice Breakers",
      "Breath Mints",
      "After Dinner Mints",
      "Chocolate Mints",
      "Peppermint Patties",
      "Candy Buttons",
      "Bottle Caps",
      "Sweet Tarts",
      "Spree",
      "Runts",
      "Gobstoppers",
      "Wonka Bar",
      "Sugar Daddy",
      "Sugar Babies",
      "Bit-O-Honey",
      "Mary Janes",
      "Necco Wafers",
      "Good & Plenty",
    ],
  },
  {
    id: "songs",
    name: "🎵 Pop Songs",
    prompt: "popular songs",
    options: [
      "Bohemian Rhapsody",
      "Thriller",
      "Sweet Dreams",
      "Dancing Queen",
      "Billie Jean",
      "Like a Prayer",
      "Sweet Child O' Mine",
      "Smells Like Teen Spirit",
      "I Will Always Love You",
      "Stayin' Alive",
      "Sweet Caroline",
      "Hey Jude",
      "Purple Rain",
      "Hotel California",
      "Imagine",
      "Sweet Home Alabama",
      "Don't Stop Believin'",
      "I Want to Hold Your Hand",
      "Uptown Funk",
      "Shape of You",
      "Rolling in the Deep",
      "Bad Guy",
      "Shake It Off",
      "Despacito",
      "Old Town Road",
      "Blinding Lights",
      "Watermelon Sugar",
      "Bad Romance",
      "Call Me Maybe",
      "Happy",
      "All Star",
      "Poker Face",
      "Firework",
      "Someone Like You",
      "Party Rock Anthem",
      "Get Lucky",
      "Royals",
      "All About That Bass",
      "See You Again",
      "Hello",
      "Closer",
      "Havana",
      "Thank U, Next",
      "Truth Hurts",
      "Levitating",
      "drivers license",
      "Stay",
      "As It Was",
      "Anti-Hero",
      "Hey There Delilah",
      "Umbrella",
      "Low",
      "Just Dance",
      "I Gotta Feeling",
      "Tik Tok",
      "California Gurls",
      "Rolling in the Deep",
      "We Found Love",
      "Gangnam Style",
      "Wrecking Ball",
      "Happy",
      "Blank Space",
      "Hotline Bling",
      "Sorry",
      "One Dance",
      "God's Plan",
      "Shallow",
      "7 Rings",
      "Dynamite",
      "Butter",
      "WAP",
      "Good 4 U",
      "Montero",
      "Industry Baby",
      "Heat Waves",
      "Shivers",
      "Easy On Me",
      "Stay With Me",
      "Thinking Out Loud",
      "Perfect",
      "Shape of You",
      "Castle on the Hill",
      "Galway Girl",
      "Photograph",
      "The A Team",
      "Shake It Off",
      "Love Story",
      "You Belong With Me",
      "I Knew You Were Trouble",
      "22",
      "Bad Blood",
      "Look What You Made Me Do",
      "Cardigan",
      "Willow",
      "All Too Well",
      "Born This Way",
      "Just Dance",
      "Poker Face",
      "Bad Romance",
      "Alejandro",
    ],
  },
  {
    id: "accents",
    name: "🗣️ Accents & Impressions",
    prompt: "accents and character impressions",
    options: [
      "British Accent",
      "Australian Accent",
      "Irish Accent",
      "Scottish Accent",
      "French Accent",
      "Italian Accent",
      "Russian Accent",
      "German Accent",
      "Spanish Accent",
      "Indian Accent",
      "Southern US Accent",
      "New York Accent",
      "Boston Accent",
      "Valley Girl",
      "Surfer Dude",
      "Cowboy",
      "Robot Voice",
      "Elvis Presley",
      "Arnold Schwarzenegger",
      "Donald Trump",
      "Morgan Freeman",
      "Sean Connery",
      "Christopher Walken",
      "Yoda",
      "Darth Vader",
      "Mickey Mouse",
      "Kermit the Frog",
      "Batman",
      "Pirate",
      "Dracula",
      "Gollum",
      "Homer Simpson",
      "Peter Griffin",
      "SpongeBob SquarePants",
      "Shrek",
      "Borat",
      "Queen Elizabeth",
      "Barack Obama",
      "David Attenborough",
      "Gordon Ramsay",
      "Sylvester Stallone",
      "Al Pacino",
      "Robert De Niro",
      "Jack Nicholson",
      "Matthew McConaughey",
      "Owen Wilson",
      "Nicolas Cage",
      "Jim Carrey",
      "Mike Tyson",
      "Snoop Dogg",
      "Bugs Bunny",
      "Daffy Duck",
      "Elmo",
      "Cookie Monster",
      "Barney",
      "Mario",
      "Luigi",
      "Sonic the Hedgehog",
      "Optimus Prime",
      "Megatron",
      "Stewie Griffin",
      "Mr. Burns",
      "Marge Simpson",
      "Bart Simpson",
      "Lisa Simpson",
      "Patrick Star",
      "Squidward",
      "Mr. Krabs",
      "Sandy Cheeks",
      "Plankton",
      "Tony Montana",
      "The Terminator",
      "James Bond",
      "Austin Powers",
      "Dr. Evil",
      "Gandalf",
      "Gollum",
      "Dobby",
      "Hagrid",
      "Dumbledore",
      "Marvin the Martian",
      "Foghorn Leghorn",
      "Porky Pig",
      "Tweety Bird",
      "Sylvester",
      "Scooby-Doo",
      "Shaggy",
      "Fred Flintstone",
      "Barney Rubble",
      "George Jetson",
      "Tony Stark",
      "Thor",
      "Captain America",
      "Hulk",
      "Black Widow",
      "Joker",
      "Harley Quinn",
      "Penguin",
      "Riddler",
      "Bane",
    ],
  },
  {
    id: "historical",
    name: "👑 Historical Figures",
    prompt: "famous historical figures",
    options: [
      "Albert Einstein",
      "Leonardo da Vinci",
      "William Shakespeare",
      "Napoleon Bonaparte",
      "Abraham Lincoln",
      "George Washington",
      "Martin Luther King Jr.",
      "Winston Churchill",
      "Marie Curie",
      "Cleopatra",
      "Julius Caesar",
      "Alexander the Great",
      "Mozart",
      "Beethoven",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Charles Darwin",
      "Isaac Newton",
      "Galileo Galilei",
      "Thomas Edison",
      "Benjamin Franklin",
      "Florence Nightingale",
      "Joan of Arc",
      "Christopher Columbus",
      "Marco Polo",
      "Genghis Khan",
      "Leonardo da Vinci",
      "Michelangelo",
      "Queen Victoria",
      "Henry VIII",
      "Nelson Mandela",
      "Mahatma Gandhi",
      "Mother Teresa",
      "Anne Frank",
      "Rosa Parks",
      "Helen Keller",
      "Wright Brothers",
      "Neil Armstrong",
      "Charlie Chaplin",
      "Walt Disney",
      "Aristotle",
      "Plato",
      "Socrates",
      "King Tut",
      "Catherine the Great",
      "Queen Elizabeth I",
      "Confucius",
      "Sun Tzu",
      "Nikola Tesla",
      "Marie Antoinette",
      "Harriet Tubman",
      "Susan B. Anthony",
      "Frederick Douglass",
      "Eleanor Roosevelt",
      "Louis Pasteur",
      "Sigmund Freud",
      "Jane Austen",
      "Ernest Hemingway",
      "Mark Twain",
      "Charles Dickens",
      "Frida Kahlo",
      "Mary Shelley",
      "Virginia Woolf",
      "Emily Dickinson",
      "Maya Angelou",
      "Ada Lovelace",
      "Amelia Earhart",
      "George Orwell",
      "Franz Kafka",
      "Oscar Wilde",
      "Edgar Allan Poe",
      "Emily Brontë",
      "Charlotte Brontë",
      "Mary Wollstonecraft",
      "René Descartes",
      "John Locke",
      "Karl Marx",
      "Friedrich Nietzsche",
      "Jean-Jacques Rousseau",
      "Voltaire",
      "Mary Queen of Scots",
      "Elizabeth Blackwell",
      "Clara Barton",
      "Pocahontas",
      "Sacagawea",
      "Sitting Bull",
      "Crazy Horse",
      "Geronimo",
      "Chief Joseph",
      "Booker T. Washington",
      "W.E.B. Du Bois",
      "Malcolm X",
      "Thurgood Marshall",
      "Jackie Robinson",
      "Jesse Owens",
      "Muhammad Ali",
      "Princess Diana",
      "Mother Jones",
      "Margaret Thatcher",
      "Indira Gandhi",
    ],
  },
  {
    id: "geography",
    name: "🌎 Geography",
    prompt: "U.S. States, Cities, and Countries",
    options: [
      "Mount Everest",
      "Grand Canyon",
      "Great Barrier Reef",
      "Amazon Rainforest",
      "Sahara Desert",
      "Niagara Falls",
      "Venice",
      "Paris",
      "London",
      "New York City",
      "Tokyo",
      "Sydney",
      "Rio de Janeiro",
      "Cairo",
      "Rome",
      "Great Wall of China",
      "Taj Mahal",
      "Machu Picchu",
      "Petra",
      "Stonehenge",
      "Victoria Falls",
      "Dead Sea",
      "Mount Fuji",
      "Yellowstone",
      "Antarctica",
      "Hawaii",
      "Iceland",
      "Swiss Alps",
      "Galapagos Islands",
      "Maldives",
      "Northern Lights",
      "Nile River",
      "Mount Kilimanjaro",
      "Great Plains",
      "Andes Mountains",
      "Mediterranean Sea",
      "Pacific Ocean",
      "Himalayas",
      "Serengeti",
      "Great Lakes",
      "California",
      "Texas",
      "Florida",
      "New York",
      "Alaska",
      "Montana",
      "Colorado",
      "Louisiana",
      "Massachusetts",
      "Arizona",
      "Nevada",
      "Oregon",
      "Washington",
      "Maine",
      "Brazil",
      "France",
      "Italy",
      "Spain",
      "Germany",
      "China",
      "Japan",
      "India",
      "Russia",
      "Australia",
      "Mexico",
      "Canada",
      "Egypt",
      "South Africa",
      "Argentina",
      "Greece",
      "Thailand",
      "Vietnam",
      "Morocco",
      "Peru",
      "Amsterdam",
      "Berlin",
      "Dubai",
      "Hong Kong",
      "Istanbul",
      "Jerusalem",
      "Las Vegas",
      "Moscow",
      "Mumbai",
      "Prague",
      "San Francisco",
      "Seoul",
      "Shanghai",
      "Singapore",
      "Stockholm",
      "Barcelona",
      "Vienna",
      "Athens",
      "Dublin",
      "Edinburgh",
      "Copenhagen",
      "Oslo",
      "Helsinki",
      "Warsaw",
      "Budapest",
      "Lisbon",
      "Madrid",
      "Brussels",
      "Amsterdam",
      "Zurich",
      "Geneva",
      "Milan",
      "Florence",
      "Venice",
      "Naples",
      "Munich",
      "Frankfurt",
      "Hamburg",
      "Berlin",
      "Prague",
      "Vienna",
    ],
  },
  {
    id: "books",
    name: "📚 Books",
    prompt: "book titles",
    options: [
      "Harry Potter",
      "The Lord of the Rings",
      "Pride and Prejudice",
      "To Kill a Mockingbird",
      "1984",
      "The Great Gatsby",
      "The Catcher in the Rye",
      "The Hobbit",
      "The Chronicles of Narnia",
      "Jane Eyre",
      "Wuthering Heights",
      "Little Women",
      "The Hunger Games",
      "The Da Vinci Code",
      "The Alchemist",
      "Brave New World",
      "The Odyssey",
      "Don Quixote",
      "Moby Dick",
      "Alice in Wonderland",
      "Dracula",
      "Frankenstein",
      "The Picture of Dorian Gray",
      "The Adventures of Sherlock Holmes",
      "The Count of Monte Cristo",
      "Les Misérables",
      "War and Peace",
      "Crime and Punishment",
      "One Hundred Years of Solitude",
      "The Little Prince",
      "The Grapes of Wrath",
      "The Color Purple",
      "The Handmaid's Tale",
      "The Road",
      "Life of Pi",
      "The Book Thief",
      "The Kite Runner",
      "Gone with the Wind",
      "The Secret Garden",
      "Charlotte's Web",
      "The Lion, the Witch and the Wardrobe",
      "The Fellowship of the Ring",
      "The Two Towers",
      "The Return of the King",
      "The Silmarillion",
      "Dune",
      "Foundation",
      "Ender's Game",
      "Neuromancer",
      "The Hitchhiker's Guide to the Galaxy",
      "The Stand",
      "It",
      "The Shining",
      "Pet Sematary",
      "Carrie",
      "The Girl with the Dragon Tattoo",
      "Gone Girl",
      "The Da Vinci Code",
      "Angels & Demons",
      "Inferno",
      "The Godfather",
      "Jurassic Park",
      "The Lost World",
      "The Hunt for Red October",
      "The Firm",
      "The Notebook",
      "The Fault in Our Stars",
      "Twilight",
      "New Moon",
      "Eclipse",
      "The Giver",
      "Holes",
      "Bridge to Terabithia",
      "Where the Wild Things Are",
      "Goodnight Moon",
      "The Very Hungry Caterpillar",
      "Green Eggs and Ham",
      "The Cat in the Hat",
      "Charlie and the Chocolate Factory",
      "Matilda",
      "The BFG",
      "James and the Giant Peach",
      "The Witches",
      "Fantastic Mr. Fox",
      "The Twits",
      "The Gruffalo",
      "We're Going on a Bear Hunt",
      "The Tiger Who Came to Tea",
      "Each Peach Pear Plum",
      "The Snowman",
      "The Wind in the Willows",
      "Watership Down",
      "The Tale of Peter Rabbit",
      "The Velveteen Rabbit",
      "Winnie-the-Pooh",
      "The House at Pooh Corner",
      "Stuart Little",
      "The Mouse and the Motorcycle",
      "Mrs. Frisby and the Rats of NIMH",
      "The Cricket in Times Square",
      "Anna Karenina",
      "The Canterbury Tales",
      "Paradise Lost",
      "The Divine Comedy",
      "The Iliad",
      "Beowulf",
      "The Aeneid",
      "Gulliver's Travels",
      "Robinson Crusoe",
      "The Three Musketeers",
      "The Scarlet Letter",
      "Great Expectations",
      "David Copperfield",
      "Oliver Twist",
      "A Tale of Two Cities",
      "The Adventures of Tom Sawyer",
      "The Adventures of Huckleberry Finn",
      "Uncle Tom's Cabin",
      "Madame Bovary",
      "The Brothers Karamazov",
      "The Portrait of a Lady",
      "Heart of Darkness",
      "Lord of the Flies",
      "Of Mice and Men",
      "The Old Man and the Sea",
      "For Whom the Bell Tolls",
      "The Sun Also Rises",
    ],
  },
  {
    id: "classic",
    name: "🎭 Classic Dumb Charades",
    prompt: "classic",
    options: [
      "Swimming",
      "Reading",
      "Talking on the phone",
      "Showering",
      "Brushing your teeth",
      "Eating",
      "Making your bed",
      "Smelling a flower",
      "Blowing out birthday candles",
      "Tying your shoes",
      "Walking a dog",
      "Playing video games",
      "Flying a kite",
      "Making a snow angel",
      "Building with blocks",
      "Catching butterflies",
      "Driving a car",
      "Skateboarding",
      "Flipping pancakes",
      "Whisking eggs",
      "Vacuuming",
      "Chopping wood",
      "Tap dancing",
      "Climbing a tree",
      "Sunbathing",
      "Sending a text",
      "Shoveling snow",
      "Building a sand castle",
      "Taking a selfie",
      "Blow-drying your hair",
      "Parallel parking",
      "Painting",
      "Hailing a taxi",
      "Writing a check",
      "Opening a gift",
      "Practicing yoga",
      "Typing an angry email",
      "Going down a waterfall in a barrel",
      "Boarding an airplane",
      "Putting on mascara",
      "Running on a treadmill",
      "Playing the cowbell",
      "Winning an award",
      "Sleeping in a hammock",
      "Being on a Zoom call for work",
      "Running a marathon",
      "Going to an art museum",
      "Doing a cannonball",
      "Suppressing a sneeze",
      "Losing your glasses",
      "Putting on a wig",
      "Having the hiccups",
      "Riding a bull",
      "Stubbing your toe",
      "Slipping on a banana peel",
      "Smelling something bad",
      "Bouncing on a pogo stick",
      "Pretending to be surprised",
      "Changing a diaper",
      "Eating noodles on a first date",
      "Assembling IKEA furniture",
      "Watching a baseball game where your team is losing",
      "Getting your item unstuck from a vending machine",
      "The Eiffel Tower",
      "An erupting volcano",
      "Jet lag",
      "The sun",
      "Bartender",
      "The Statue of Liberty",
      "Stage fright",
      "Pickpocket",
      "Disney World",
      "Food fight",
      "Nightmare",
      "Orchestra conductor",
      "Barista",
      "Scuba diving",
      "Doing your makeup",
      "Shopping spree",
      "Mount Rushmore",
      "Traffic jam",
      "Lifeguard",
      "Lightbulb",
      "Segway",
      "Car mechanic",
      "Dentures",
      "Brain freeze",
      "Bankruptcy",
      "Bigfoot",
      "Dragon",
      "Yodeling",
      "Sudoku",
      "Alien abduction",
      "Time travel",
      "Black hole",
      "Cabbage",
      "Playing charades",
      "Procrastination",
      "Global warming",
      "Deja vu",
      "Identity theft",
    ],
  },
  {
    id: "idioms",
    name: "💬 Idioms",
    prompt: "idioms",
    options: [
      "Jumping for joy",
      "Walking on eggshells",
      "Kicking the bucket",
      "Biting your tongue",
      "Raining cats and dogs",
      "Crying over spilled milk",
      "Throwing in the towel",
      "Spilling the beans",
      "Hitting the nail on the head",
      "Breaking the ice",
      "Reading between the lines",
      "Playing it by ear",
      "Cat got your tongue",
      "Burned to a crisp",
      "Fighting fire with fire",
      "Couch potato",
      "Dancing in the rain",
      "Painting the town red",
      "Singing in the shower",
      "Pushing up daisies",
      "Bringing home the bacon",
      "Chasing your tail",
      "Letting the cat out of the bag",
      "Barking up the wrong tree",
      "Riding the wave",
      "Rolling with the punches",
      "Two peas in a pod",
      "Catching lightning in a bottle",
      "Blowing your own trumpet",
      "Pulling your leg",
      "Fishing for compliments",
      "Catching your breath",
      "Building a sandcastle",
      "Losing your marbles",
      "Wearing your heart on your sleeve",
      "Banging your head against the wall",
      "Sitting on the fence",
      "Kicking up a fuss",
      "Making a mountain out of a molehill",
      "Holding your horses",
      "Crying wolf",
      "Having a chip on your shoulder",
      "Digging your own grave",
      "Hanging by a thread",
      "Throwing caution to the wind",
      "Sticking your neck out",
      "Sweeping it under the rug",
      "Hitting the road",
      "Walking on thin ice",
      "Flying under the radar",
      "Tying the knot",
      "Cutting corners",
      "Stepping up to the plate",
      "Biting the bullet",
      "Making waves",
      "Getting cold feet",
      "Rocking the boat",
      "Testing the waters",
      "Opening a can of worms",
      "Cutting to the chase",
      "Picking up the pieces",
      "Running around in circles",
      "Splitting hairs",
      "Eating humble pie",
      "Blowing hot and cold",
      "Shaking like a leaf",
      "Throwing your weight around",
      "Washing your hands of something",
      "Breaking the bank",
      "Chewing the fat",
      "Jumping the gun",
      "Driving up the wall",
      "Eating someone alive",
      "Fanning the flames",
      "Giving the cold shoulder",
      "Hitting a wall",
      "Jumping through hoops",
      "Knocking it out of the park",
      "Laughing your head off",
      "Making a big splash",
      "Milking it for all it's worth",
      "Pulling a rabbit out of a hat",
      "Pushing the envelope",
      "Ruffling feathers",
      "Running out of steam",
      "Showing your true colors",
      "Spreading your wings",
      "Standing on your toes",
      "Stealing the show",
      "Throwing down the gauntlet",
      "Turning over a new leaf",
      "Walking a tightrope",
      "Wearing many hats",
      "Wiping the slate clean",
      "Add fuel to the fire",
      "At the drop of a hat",
      "Back to square one",
      "Barking up the wrong tree",
      "Beat around the bush",
      "Bite off more than you can chew",
      "Blow off some steam",
      "Break the mold",
      "Burst your bubble",
      "By the skin of your teeth",
      "Call it a day",
      "Cast the first stone",
      "Chip off the old block",
      "Close but no cigar",
      "Cold as ice",
      "Cook up a storm",
      "Cry over spilled milk",
      "Curiosity killed the cat",
      "Cut and dry",
      "Devil's advocate",
      "Dodge a bullet",
      "Don't cry wolf",
      "Drop the ball",
      "Eager beaver",
      "Eat your words",
      "Face the music",
      "Feather in your cap",
      "Fight tooth and nail",
      "Fit as a fiddle",
      "Flip the script",
      "Fly by the seat of your pants",
      "Go the extra mile",
      "Golden opportunity",
      "Grain of salt",
      "Green thumb",
      "Hang in there",
      "Happy as a clam",
      "Have a cow",
      "Have your cake and eat it too",
      "Head over heels",
      "Heart of gold",
      "Hit the sack",
      "Hold your horses",
      "Hot potato",
      "In the same boat",
      "Jack of all trades",
      "Jump to conclusions",
      "Keep your chin up",
      "Kill two birds with one stone",
      "Lay down the law",
      "Let bygones be bygones",
      "Live and let live",
      "Make ends meet",
      "Make hay while the sun shines",
      "Miss the boat",
      "Not playing with a full deck",
      "Off the beaten path",
      "Once in a blue moon",
      "Out of the frying pan into the fire",
      "Piece of cake",
      "Pull yourself together",
      "Rain on your parade",
      "Reap what you sow",
      "Rise and shine",
      "Shoot for the stars",
      "Skeletons in the closet",
      "Snug as a bug in a rug",
      "Spill the tea",
      "Stay on your toes",
      "Strike while the iron is hot",
      "Take it with a grain of salt",
      "The ball is in your court",
      "The calm before the storm",
      "The icing on the cake",
      "Throw a wrench in the works",
      "Time flies when you're having fun",
      "Turn the tables",
      "Under the weather",
      "Water under the bridge",
      "When pigs fly",
      "Wild goose chase",
      "You can't judge a book by its cover",
      "Zip your lip",
    ],
  },
  {
    id: "custom",
    name: "🎯 Custom",
    prompt: "",
  },
] as const;

export const getRandomOptionsForCategory = (
  categoryId: string,
  count: number
): string[] => {
  if (categoryId === "misc") {
    // For misc, get random options from all categories that have options
    const allOptions = CATEGORIES.filter(
      (cat) => cat.options && cat.id !== "misc" && cat.id !== "custom"
    ).flatMap((cat) => cat.options!);
    return shuffleArray([...allOptions]).slice(0, count);
  }

  if (categoryId === "custom") {
    return [];
  }

  const category = CATEGORIES.find((cat) => cat.id === categoryId);
  const categoryOptions = category?.options || [];
  return shuffleArray([...categoryOptions]).slice(0, count);
};

const shuffleArray = <T>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

// Export for use in other files
export const ALL_CATEGORIES = CATEGORIES;
