interface Category {
  id: string;
  name: string;
  prompt: string;
  options?: string[];
}

export const CATEGORIES: Category[] = [
  {
    id: "misc",
    name: "🎲 All Categories",
    prompt: "mixed variety of charades-friendly topics",
  },
  {
    id: "movies",
    name: "🎬 TV Shows & Movies",
    prompt: "popular TV shows and movies",
    options: [
      "Breaking Bad",
      "The Office",
      "Friends",
      "Stranger Things",
      "Game of Thrones",
      "Star Wars",
      "Harry Potter",
      "The Matrix",
      "Jurassic Park",
      "The Lion King",
      "Titanic",
      "Avatar",
      "The Avengers",
      "Lord of the Rings",
      "Finding Nemo",
      "The Simpsons",
      "Seinfeld",
      "The Walking Dead",
      "Black Mirror",
      "Squid Game",
      "Inception",
      "Forrest Gump",
      "The Godfather",
      "Pulp Fiction",
      "Fight Club",
      "The Dark Knight",
      "Jaws",
      "E.T.",
      "Back to the Future",
      "Indiana Jones",
      "The Shawshank Redemption",
      "The Wizard of Oz",
      "Ghostbusters",
      "The Terminator",
      "Toy Story",
      "The Silence of the Lambs",
      "Gladiator",
      "The Big Bang Theory",
      "How I Met Your Mother",
      "Modern Family",
      "The Crown",
      "Bridgerton",
      "The Mandalorian",
      "The Last of Us",
      "Wednesday",
      "The Boys",
      "Better Call Saul",
      "Dexter",
      "Lost",
      "The Wire",
      "Mad Men",
      "The Sopranos",
      "Frasier",
      "Cheers",
      "The X-Files",
      "Twin Peaks",
      "The Twilight Zone",
      "The Good Place",
      "Parks and Recreation",
      "Brooklyn Nine-Nine",
      "The Office UK",
      "Downton Abbey",
      "Westworld",
      "True Detective",
      "Chernobyl",
      "Band of Brothers",
      "The Pacific",
      "Planet Earth",
      "Blue Planet",
      "Cosmos",
      "The Witcher",
      "House of the Dragon",
      "Succession",
      "Ted Lasso",
      "Abbott Elementary",
      "Schitt's Creek",
      "The Bear",
      "Fleabag",
      "Killing Eve",
      "Ozark",
      "Narcos",
      "Money Heist",
      "Dark",
      "The Umbrella Academy",
      "Daredevil",
      "Jessica Jones",
      "WandaVision",
      "Loki",
      "Moon Knight",
      "Ms. Marvel",
      "Andor",
      "House of Cards",
      "The Americans",
      "Homeland",
      "24",
      "Prison Break",
      "Grey's Anatomy",
      "ER",
      "House",
      "The Good Doctor",
      "This Is Us",
      "The Handmaid's Tale",
      "Black Books",
      "Father Ted",
      "The IT Crowd",
      "Peep Show",
      "Only Murders in the Building",
      "The White Lotus",
      "Yellowjackets",
      "Severance",
      "The Morning Show",
    ],
  },
  {
    id: "disney",
    name: "🏰 Disney Characters",
    prompt: "Disney and Pixar characters",
    options: [
      "Mickey Mouse",
      "Donald Duck",
      "Goofy",
      "Minnie Mouse",
      "Pluto",
      "Snow White",
      "Cinderella",
      "Ariel",
      "Belle",
      "Jasmine",
      "Aladdin",
      "Simba",
      "Timon",
      "Pumbaa",
      "Woody",
      "Buzz Lightyear",
      "Nemo",
      "Dory",
      "Elsa",
      "Anna",
      "Olaf",
      "Moana",
      "Maui",
      "Mulan",
      "Mushu",
      "Peter Pan",
      "Captain Hook",
      "Tinker Bell",
      "Winnie the Pooh",
      "Tigger",
      "Piglet",
      "Eeyore",
      "Rabbit",
      "Roo",
      "Kanga",
      "Bambi",
      "Thumper",
      "Dumbo",
      "Timothy Mouse",
      "Pinocchio",
      "Jiminy Cricket",
      "Geppetto",
      "Mowgli",
      "Baloo",
      "Bagheera",
      "King Louie",
      "Shere Khan",
      "Robin Hood",
      "Little John",
      "Maid Marian",
      "Merida",
      "Rapunzel",
      "Flynn Rider",
      "Pascal",
      "Maximus",
      "Hercules",
      "Meg",
      "Phil",
      "Zeus",
      "Hades",
      "Pocahontas",
      "John Smith",
      "Meeko",
      "Flit",
      "Governor Ratcliffe",
      "Tarzan",
      "Jane",
      "Terk",
      "Tantor",
      "Clayton",
      "Lilo",
      "Stitch",
      "Nani",
      "Pleakley",
      "Jumba",
      "Remy",
      "Linguini",
      "Colette",
      "Anton Ego",
      "Emile",
      "WALL-E",
      "EVE",
      "M-O",
      "AUTO",
      "Captain B. McCrea",
      "Carl Fredricksen",
      "Russell",
      "Dug",
      "Kevin",
      "Charles Muntz",
      "Judy Hopps",
      "Nick Wilde",
      "Flash",
      "Chief Bogo",
      "Bellwether",
      "Hiro Hamada",
      "Baymax",
      "GoGo",
      "Honey Lemon",
      "Fred",
      "Miguel",
      "Héctor",
      "Mama Coco",
      "Dante",
      "Ernesto de la Cruz",
      "Joy",
      "Sadness",
      "Anger",
      "Fear",
      "Disgust",
      "Bing Bong",
      "Riley",
      "Ian Lightfoot",
      "Barley Lightfoot",
      "The Manticore",
    ],
  },
  {
    id: "superheroes",
    name: "🦸‍♂️ Superheroes",
    prompt: "popular superheroes (especially Marvel)",
    options: [
      "Spider-Man",
      "Batman",
      "Superman",
      "Wonder Woman",
      "Iron Man",
      "Captain America",
      "Thor",
      "Hulk",
      "Black Widow",
      "Black Panther",
      "Doctor Strange",
      "Wolverine",
      "Deadpool",
      "Flash",
      "Green Lantern",
      "Aquaman",
      "Ant-Man",
      "Captain Marvel",
      "Hawkeye",
      "Vision",
      "Scarlet Witch",
      "Loki",
      "Thanos",
      "Star-Lord",
      "Groot",
      "Rocket Raccoon",
      "Professor X",
      "Magneto",
      "Storm",
      "Jean Grey",
      "Cyclops",
      "Beast",
      "Rogue",
      "Gambit",
      "Nightcrawler",
      "Daredevil",
      "Punisher",
      "Ghost Rider",
      "Blade",
      "Moon Knight",
      "She-Hulk",
      "Ms. Marvel",
      "Miles Morales",
      "Spider-Gwen",
      "Venom",
      "Carnage",
      "Doctor Doom",
      "Green Goblin",
      "Joker",
      "Harley Quinn",
      "Catwoman",
      "Penguin",
      "Riddler",
      "Two-Face",
      "Poison Ivy",
      "Lex Luthor",
      "Brainiac",
      "General Zod",
      "Darkseid",
      "Doomsday",
      "Red Skull",
      "Winter Soldier",
      "Ultron",
      "Hela",
      "Killmonger",
      "Doctor Octopus",
      "Sandman",
      "Mysterio",
      "Vulture",
      "Electro",
      "Phoenix",
      "Apocalypse",
      "Juggernaut",
      "Sabretooth",
      "Mystique",
      "Black Adam",
      "Shazam",
      "Constantine",
      "Batgirl",
      "Supergirl",
      "Robin",
      "Nightwing",
      "Red Hood",
      "Batwoman",
      "Oracle",
      "Nick Fury",
      "Maria Hill",
      "Phil Coulson",
      "Jessica Jones",
      "Luke Cage",
      "Iron Fist",
      "Black Bolt",
      "Medusa",
      "Crystal",
      "Karnak",
      "Blue Beetle",
      "Booster Gold",
      "Zatanna",
      "Black Canary",
      "Green Arrow",
      "Martian Manhunter",
      "Cyborg",
      "Beast Boy",
      "Starfire",
      "Raven",
      "Kid Flash",
      "Superboy",
      "Wonder Girl",
      "Aqualad",
      "Speedy",
    ],
  },
  {
    id: "celebrities",
    name: "⭐ Celebrities",
    prompt: "famous celebrities",
    options: [
      "Tom Hanks",
      "Morgan Freeman",
      "Leonardo DiCaprio",
      "Brad Pitt",
      "Jennifer Lawrence",
      "Meryl Streep",
      "Will Smith",
      "Johnny Depp",
      "Taylor Swift",
      "Beyoncé",
      "Lady Gaga",
      "Justin Bieber",
      "Drake",
      "Adele",
      "Ed Sheeran",
      "Rihanna",
      "Barack Obama",
      "Donald Trump",
      "Elon Musk",
      "Bill Gates",
      "Mark Zuckerberg",
      "Oprah Winfrey",
      "Ellen DeGeneres",
      "Jimmy Fallon",
      "Gordon Ramsay",
      "David Beckham",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Michael Jordan",
      "LeBron James",
      "Serena Williams",
      "Michael Phelps",
      "Albert Einstein",
      "Stephen Hawking",
      "Pablo Picasso",
      "Vincent van Gogh",
      "Madonna",
      "Michael Jackson",
      "Elvis Presley",
      "Bob Marley",
      "Ariana Grande",
      "Bruno Mars",
      "Katy Perry",
      "Eminem",
      "Kanye West",
      "Kim Kardashian",
      "Jennifer Aniston",
      "Robert Downey Jr",
      "Chris Hemsworth",
      "Scarlett Johansson",
      "Dwayne Johnson",
      "Ryan Reynolds",
      "Emma Watson",
      "Daniel Radcliffe",
      "Justin Timberlake",
      "Britney Spears",
      "Selena Gomez",
      "Miley Cyrus",
      "Zendaya",
      "Tom Holland",
      "Billie Eilish",
      "Post Malone",
      "Cardi B",
      "Kendrick Lamar",
      "Harry Styles",
      "Chris Pratt",
      "Margot Robbie",
      "Gal Gadot",
      "Keanu Reeves",
      "Tom Cruise",
      "Julia Roberts",
      "Sandra Bullock",
      "Nicole Kidman",
      "Hugh Jackman",
      "Russell Crowe",
      "Angelina Jolie",
      "George Clooney",
      "Matt Damon",
      "Ben Affleck",
      "Jennifer Lopez",
      "Shakira",
      "Justin Trudeau",
      "Queen Elizabeth II",
      "Prince William",
      "Kate Middleton",
      "Prince Harry",
      "Meghan Markle",
      "David Attenborough",
      "Michelle Obama",
      "Joe Biden",
      "Kamala Harris",
      "Alexandria Ocasio-Cortez",
      "Bernie Sanders",
      "Arnold Schwarzenegger",
      "Jackie Chan",
      "Bruce Lee",
      "Morgan Freeman",
      "Samuel L. Jackson",
      "Denzel Washington",
      "Will Ferrell",
    ],
  },
  {
    id: "animals",
    name: "🦁 Animals",
    prompt: "animals",
    options: [
      "Lion",
      "Elephant",
      "Giraffe",
      "Monkey",
      "Penguin",
      "Kangaroo",
      "Koala",
      "Panda",
      "Tiger",
      "Bear",
      "Wolf",
      "Fox",
      "Deer",
      "Zebra",
      "Hippopotamus",
      "Rhinoceros",
      "Crocodile",
      "Snake",
      "Eagle",
      "Owl",
      "Parrot",
      "Flamingo",
      "Octopus",
      "Dolphin",
      "Shark",
      "Whale",
      "Butterfly",
      "Spider",
      "Ant",
      "Bee",
      "Sloth",
      "Platypus",
      "Peacock",
      "Ostrich",
      "Gorilla",
      "Cheetah",
      "Camel",
      "Seal",
      "Polar Bear",
      "Penguin",
      "Hamster",
      "Guinea Pig",
      "Rabbit",
      "Cat",
      "Dog",
      "Horse",
      "Cow",
      "Pig",
      "Sheep",
      "Goat",
      "Chicken",
      "Rooster",
      "Duck",
      "Goose",
      "Turkey",
      "Pigeon",
      "Seagull",
      "Crow",
      "Raven",
      "Blue Jay",
      "Cardinal",
      "Hummingbird",
      "Woodpecker",
      "Pelican",
      "Swan",
      "Toucan",
      "Macaw",
      "Cockatoo",
      "Iguana",
      "Chameleon",
      "Gecko",
      "Turtle",
      "Tortoise",
      "Frog",
      "Toad",
      "Salamander",
      "Newt",
      "Fish",
      "Goldfish",
      "Clownfish",
      "Seahorse",
      "Starfish",
      "Jellyfish",
      "Crab",
      "Lobster",
      "Shrimp",
      "Squid",
      "Snail",
      "Slug",
      "Ladybug",
      "Praying Mantis",
      "Grasshopper",
      "Cricket",
      "Caterpillar",
      "Dragonfly",
      "Mosquito",
      "Fly",
      "Wasp",
      "Hornet",
      "Scorpion",
      "Tarantula",
      "Centipede",
      "Millipede",
      "Raccoon",
      "Skunk",
      "Squirrel",
      "Chipmunk",
      "Beaver",
      "Otter",
      "Badger",
      "Hedgehog",
      "Armadillo",
      "Opossum",
      "Mole",
      "Bat",
    ],
  },
  {
    id: "food",
    name: "🍕 Food",
    prompt: "ingredients and dishes",
    options: [
      "Pizza",
      "Hamburger",
      "Sushi",
      "Spaghetti",
      "Taco",
      "Ice Cream",
      "Chocolate Cake",
      "French Fries",
      "Hot Dog",
      "Pancakes",
      "Waffles",
      "Donut",
      "Cookie",
      "Sandwich",
      "Salad",
      "Soup",
      "Steak",
      "Chicken Wings",
      "Burrito",
      "Nachos",
      "Popcorn",
      "Apple Pie",
      "Cupcake",
      "Croissant",
      "Ramen",
      "Fried Rice",
      "Curry",
      "Lasagna",
      "Mac and Cheese",
      "Grilled Cheese",
      "Peanut Butter & Jelly",
      "Cereal",
      "Oatmeal",
      "Yogurt",
      "Banana Split",
      "Milkshake",
      "Smoothie",
      "Orange Juice",
      "Coffee",
      "Tea",
      "Lemonade",
      "Soda",
      "Water",
      "Beer",
      "Wine",
      "Cocktail",
      "Martini",
      "Margarita",
      "Mojito",
      "Bloody Mary",
      "Chicken Noodle Soup",
      "Tomato Soup",
      "French Onion Soup",
      "Clam Chowder",
      "Minestrone",
      "Caesar Salad",
      "Greek Salad",
      "Cobb Salad",
      "Potato Salad",
      "Coleslaw",
      "Mashed Potatoes",
      "Baked Potato",
      "Sweet Potato Fries",
      "Onion Rings",
      "Chicken Nuggets",
      "Fish and Chips",
      "Shrimp Cocktail",
      "Lobster Roll",
      "Crab Cake",
      "Salmon",
      "Tuna",
      "Swordfish",
      "Cod",
      "Halibut",
      "Tilapia",
      "Beef Stew",
      "Chili",
      "Gumbo",
      "Jambalaya",
      "Paella",
      "Pad Thai",
      "Spring Roll",
      "Egg Roll",
      "Dumpling",
      "Dim Sum",
      "Fried Chicken",
      "Roast Chicken",
      "Turkey",
      "Ham",
      "Bacon",
      "Eggs Benedict",
      "Omelet",
      "Scrambled Eggs",
      "Sunny Side Up",
      "Hard Boiled Egg",
      "Toast",
      "Bagel",
      "English Muffin",
      "Biscuit",
      "Cornbread",
      "Brownie",
      "Chocolate Chip Cookie",
      "Sugar Cookie",
      "Oatmeal Raisin Cookie",
      "Snickerdoodle",
      "Cheesecake",
      "Tiramisu",
      "Crème Brûlée",
      "Pudding",
      "Jell-O",
      "Cotton Candy",
      "Candy Corn",
      "Gummy Bears",
      "M&Ms",
      "Skittles",
    ],
  },
  {
    id: "songs",
    name: "🎵 Pop Songs",
    prompt: "popular songs",
    options: [
      "Bohemian Rhapsody",
      "Thriller",
      "Sweet Dreams",
      "Dancing Queen",
      "Billie Jean",
      "Like a Prayer",
      "Sweet Child O' Mine",
      "Smells Like Teen Spirit",
      "I Will Always Love You",
      "Stayin' Alive",
      "Sweet Caroline",
      "Hey Jude",
      "Purple Rain",
      "Hotel California",
      "Imagine",
      "Sweet Home Alabama",
      "Don't Stop Believin'",
      "I Want to Hold Your Hand",
      "Uptown Funk",
      "Shape of You",
      "Rolling in the Deep",
      "Bad Guy",
      "Shake It Off",
      "Despacito",
      "Old Town Road",
      "Blinding Lights",
      "Watermelon Sugar",
      "Bad Romance",
      "Call Me Maybe",
      "Happy",
      "All Star",
      "Poker Face",
      "Firework",
      "Someone Like You",
      "Party Rock Anthem",
      "Get Lucky",
      "Royals",
      "All About That Bass",
      "See You Again",
      "Hello",
      "Closer",
      "Havana",
      "Thank U, Next",
      "Truth Hurts",
      "Levitating",
      "drivers license",
      "Stay",
      "As It Was",
      "Anti-Hero",
      "Hey There Delilah",
      "Umbrella",
      "Low",
      "Just Dance",
      "I Gotta Feeling",
      "Tik Tok",
      "California Gurls",
      "Rolling in the Deep",
      "We Found Love",
      "Gangnam Style",
      "Wrecking Ball",
      "Happy",
      "Blank Space",
      "Hotline Bling",
      "Sorry",
      "One Dance",
      "God's Plan",
      "Shallow",
      "7 Rings",
      "Dynamite",
      "Butter",
      "WAP",
      "Good 4 U",
      "Montero",
      "Industry Baby",
      "Heat Waves",
      "Shivers",
      "Easy On Me",
      "Stay With Me",
      "Thinking Out Loud",
      "Perfect",
      "Shape of You",
      "Castle on the Hill",
      "Galway Girl",
      "Photograph",
      "The A Team",
      "Shake It Off",
      "Love Story",
      "You Belong With Me",
      "I Knew You Were Trouble",
      "22",
      "Bad Blood",
      "Look What You Made Me Do",
      "Cardigan",
      "Willow",
      "All Too Well",
      "Born This Way",
      "Just Dance",
      "Poker Face",
      "Bad Romance",
      "Alejandro",
    ],
  },
  {
    id: "accents",
    name: "🗣️ Accents & Impressions",
    prompt: "accents and character impressions",
    options: [
      "British Accent",
      "Australian Accent",
      "Irish Accent",
      "Scottish Accent",
      "French Accent",
      "Italian Accent",
      "Russian Accent",
      "German Accent",
      "Spanish Accent",
      "Indian Accent",
      "Southern US Accent",
      "New York Accent",
      "Boston Accent",
      "Valley Girl",
      "Surfer Dude",
      "Cowboy",
      "Robot Voice",
      "Elvis Presley",
      "Arnold Schwarzenegger",
      "Donald Trump",
      "Morgan Freeman",
      "Sean Connery",
      "Christopher Walken",
      "Yoda",
      "Darth Vader",
      "Mickey Mouse",
      "Kermit the Frog",
      "Batman",
      "Pirate",
      "Dracula",
      "Gollum",
      "Homer Simpson",
      "Peter Griffin",
      "SpongeBob SquarePants",
      "Shrek",
      "Borat",
      "Queen Elizabeth",
      "Barack Obama",
      "David Attenborough",
      "Gordon Ramsay",
      "Sylvester Stallone",
      "Al Pacino",
      "Robert De Niro",
      "Jack Nicholson",
      "Matthew McConaughey",
      "Owen Wilson",
      "Nicolas Cage",
      "Jim Carrey",
      "Mike Tyson",
      "Snoop Dogg",
      "Bugs Bunny",
      "Daffy Duck",
      "Elmo",
      "Cookie Monster",
      "Barney",
      "Mario",
      "Luigi",
      "Sonic the Hedgehog",
      "Optimus Prime",
      "Megatron",
      "Stewie Griffin",
      "Mr. Burns",
      "Marge Simpson",
      "Bart Simpson",
      "Lisa Simpson",
      "Patrick Star",
      "Squidward",
      "Mr. Krabs",
      "Sandy Cheeks",
      "Plankton",
      "Tony Montana",
      "The Terminator",
      "James Bond",
      "Austin Powers",
      "Dr. Evil",
      "Gandalf",
      "Gollum",
      "Dobby",
      "Hagrid",
      "Dumbledore",
      "Marvin the Martian",
      "Foghorn Leghorn",
      "Porky Pig",
      "Tweety Bird",
      "Sylvester",
      "Scooby-Doo",
      "Shaggy",
      "Fred Flintstone",
      "Barney Rubble",
      "George Jetson",
      "Tony Stark",
      "Thor",
      "Captain America",
      "Hulk",
      "Black Widow",
      "Joker",
      "Harley Quinn",
      "Penguin",
      "Riddler",
      "Bane",
    ],
  },
  {
    id: "historical",
    name: "👑 Historical Figures",
    prompt: "famous historical figures",
    options: [
      "Albert Einstein",
      "Leonardo da Vinci",
      "William Shakespeare",
      "Napoleon Bonaparte",
      "Abraham Lincoln",
      "George Washington",
      "Martin Luther King Jr.",
      "Winston Churchill",
      "Marie Curie",
      "Cleopatra",
      "Julius Caesar",
      "Alexander the Great",
      "Mozart",
      "Beethoven",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Charles Darwin",
      "Isaac Newton",
      "Galileo Galilei",
      "Thomas Edison",
      "Benjamin Franklin",
      "Florence Nightingale",
      "Joan of Arc",
      "Christopher Columbus",
      "Marco Polo",
      "Genghis Khan",
      "Leonardo da Vinci",
      "Michelangelo",
      "Queen Victoria",
      "Henry VIII",
      "Nelson Mandela",
      "Mahatma Gandhi",
      "Mother Teresa",
      "Anne Frank",
      "Rosa Parks",
      "Helen Keller",
      "Wright Brothers",
      "Neil Armstrong",
      "Charlie Chaplin",
      "Walt Disney",
      "Aristotle",
      "Plato",
      "Socrates",
      "King Tut",
      "Catherine the Great",
      "Queen Elizabeth I",
      "Confucius",
      "Sun Tzu",
      "Nikola Tesla",
      "Marie Antoinette",
      "Harriet Tubman",
      "Susan B. Anthony",
      "Frederick Douglass",
      "Eleanor Roosevelt",
      "Louis Pasteur",
      "Sigmund Freud",
      "Jane Austen",
      "Ernest Hemingway",
      "Mark Twain",
      "Charles Dickens",
      "Frida Kahlo",
      "Mary Shelley",
      "Virginia Woolf",
      "Emily Dickinson",
      "Maya Angelou",
      "Ada Lovelace",
      "Amelia Earhart",
      "George Orwell",
      "Franz Kafka",
      "Oscar Wilde",
      "Edgar Allan Poe",
      "Emily Brontë",
      "Charlotte Brontë",
      "Mary Wollstonecraft",
      "René Descartes",
      "John Locke",
      "Karl Marx",
      "Friedrich Nietzsche",
      "Jean-Jacques Rousseau",
      "Voltaire",
      "Mary Queen of Scots",
      "Elizabeth Blackwell",
      "Clara Barton",
      "Pocahontas",
      "Sacagawea",
      "Sitting Bull",
      "Crazy Horse",
      "Geronimo",
      "Chief Joseph",
      "Booker T. Washington",
      "W.E.B. Du Bois",
      "Malcolm X",
      "Thurgood Marshall",
      "Jackie Robinson",
      "Jesse Owens",
      "Muhammad Ali",
      "Princess Diana",
      "Mother Jones",
      "Margaret Thatcher",
      "Indira Gandhi",
    ],
  },
  {
    id: "geography",
    name: "🌎 Geography",
    prompt: "U.S. States, Cities, and Countries",
    options: [
      "Mount Everest",
      "Grand Canyon",
      "Great Barrier Reef",
      "Amazon Rainforest",
      "Sahara Desert",
      "Niagara Falls",
      "Venice",
      "Paris",
      "London",
      "New York City",
      "Tokyo",
      "Sydney",
      "Rio de Janeiro",
      "Cairo",
      "Rome",
      "Great Wall of China",
      "Taj Mahal",
      "Machu Picchu",
      "Petra",
      "Stonehenge",
      "Victoria Falls",
      "Dead Sea",
      "Mount Fuji",
      "Yellowstone",
      "Antarctica",
      "Hawaii",
      "Iceland",
      "Swiss Alps",
      "Galapagos Islands",
      "Maldives",
      "Northern Lights",
      "Nile River",
      "Mount Kilimanjaro",
      "Great Plains",
      "Andes Mountains",
      "Mediterranean Sea",
      "Pacific Ocean",
      "Himalayas",
      "Serengeti",
      "Great Lakes",
      "California",
      "Texas",
      "Florida",
      "New York",
      "Alaska",
      "Montana",
      "Colorado",
      "Louisiana",
      "Massachusetts",
      "Arizona",
      "Nevada",
      "Oregon",
      "Washington",
      "Maine",
      "Brazil",
      "France",
      "Italy",
      "Spain",
      "Germany",
      "China",
      "Japan",
      "India",
      "Russia",
      "Australia",
      "Mexico",
      "Canada",
      "Egypt",
      "South Africa",
      "Argentina",
      "Greece",
      "Thailand",
      "Vietnam",
      "Morocco",
      "Peru",
      "Amsterdam",
      "Berlin",
      "Dubai",
      "Hong Kong",
      "Istanbul",
      "Jerusalem",
      "Las Vegas",
      "Moscow",
      "Mumbai",
      "Prague",
      "San Francisco",
      "Seoul",
      "Shanghai",
      "Singapore",
      "Stockholm",
      "Barcelona",
      "Vienna",
      "Athens",
      "Dublin",
      "Edinburgh",
      "Copenhagen",
      "Oslo",
      "Helsinki",
      "Warsaw",
      "Budapest",
      "Lisbon",
      "Madrid",
      "Brussels",
      "Amsterdam",
      "Zurich",
      "Geneva",
      "Milan",
      "Florence",
      "Venice",
      "Naples",
      "Munich",
      "Frankfurt",
      "Hamburg",
      "Berlin",
      "Prague",
      "Vienna",
    ],
  },
  {
    id: "books",
    name: "📚 Books",
    prompt: "book titles",
    options: [
      "Harry Potter",
      "The Lord of the Rings",
      "Pride and Prejudice",
      "To Kill a Mockingbird",
      "1984",
      "The Great Gatsby",
      "The Catcher in the Rye",
      "The Hobbit",
      "The Chronicles of Narnia",
      "Jane Eyre",
      "Wuthering Heights",
      "Little Women",
      "The Hunger Games",
      "The Da Vinci Code",
      "The Alchemist",
      "Brave New World",
      "The Odyssey",
      "Don Quixote",
      "Moby Dick",
      "Alice in Wonderland",
      "Dracula",
      "Frankenstein",
      "The Picture of Dorian Gray",
      "The Adventures of Sherlock Holmes",
      "The Count of Monte Cristo",
      "Les Misérables",
      "War and Peace",
      "Crime and Punishment",
      "One Hundred Years of Solitude",
      "The Little Prince",
      "The Grapes of Wrath",
      "The Color Purple",
      "The Handmaid's Tale",
      "The Road",
      "Life of Pi",
      "The Book Thief",
      "The Kite Runner",
      "Gone with the Wind",
      "The Secret Garden",
      "Charlotte's Web",
      "The Lion, the Witch and the Wardrobe",
      "The Fellowship of the Ring",
      "The Two Towers",
      "The Return of the King",
      "The Silmarillion",
      "Dune",
      "Foundation",
      "Ender's Game",
      "Neuromancer",
      "The Hitchhiker's Guide to the Galaxy",
      "The Stand",
      "It",
      "The Shining",
      "Pet Sematary",
      "Carrie",
      "The Girl with the Dragon Tattoo",
      "Gone Girl",
      "The Da Vinci Code",
      "Angels & Demons",
      "Inferno",
      "The Godfather",
      "Jurassic Park",
      "The Lost World",
      "The Hunt for Red October",
      "The Firm",
      "The Notebook",
      "The Fault in Our Stars",
      "Twilight",
      "New Moon",
      "Eclipse",
      "The Giver",
      "Holes",
      "Bridge to Terabithia",
      "Where the Wild Things Are",
      "Goodnight Moon",
      "The Very Hungry Caterpillar",
      "Green Eggs and Ham",
      "The Cat in the Hat",
      "Charlie and the Chocolate Factory",
      "Matilda",
      "The BFG",
      "James and the Giant Peach",
      "The Witches",
      "Fantastic Mr. Fox",
      "The Twits",
      "The Gruffalo",
      "We're Going on a Bear Hunt",
      "The Tiger Who Came to Tea",
      "Each Peach Pear Plum",
      "The Snowman",
      "The Wind in the Willows",
      "Watership Down",
      "The Tale of Peter Rabbit",
      "The Velveteen Rabbit",
      "Winnie-the-Pooh",
      "The House at Pooh Corner",
      "Stuart Little",
      "The Mouse and the Motorcycle",
      "Mrs. Frisby and the Rats of NIMH",
      "The Cricket in Times Square",
    ],
  },
  {
    id: "idioms",
    name: "💬 Idioms",
    prompt: "idioms",
    options: [
      "Jumping for joy",
      "Walking on eggshells",
      "Kicking the bucket",
      "Biting your tongue",
      "Raining cats and dogs",
      "Crying over spilled milk",
      "Throwing in the towel",
      "Spilling the beans",
      "Hitting the nail on the head",
      "Breaking the ice",
      "Reading between the lines",
      "Playing it by ear",
      "Cat got your tongue",
      "Burned to a crisp",
      "Fighting fire with fire",
      "Couch potato",
      "Dancing in the rain",
      "Painting the town red",
      "Singing in the shower",
      "Pushing up daisies",
      "Bringing home the bacon",
      "Chasing your tail",
      "Letting the cat out of the bag",
      "Barking up the wrong tree",
      "Riding the wave",
      "Rolling with the punches",
      "Two peas in a pod",
      "Catching lightning in a bottle",
      "Blowing your own trumpet",
      "Pulling your leg",
      "Fishing for compliments",
      "Catching your breath",
      "Building a sandcastle",
      "Losing your marbles",
      "Wearing your heart on your sleeve",
      "Banging your head against the wall",
      "Sitting on the fence",
      "Kicking up a fuss",
      "Making a mountain out of a molehill",
      "Holding your horses",
      "Crying wolf",
      "Having a chip on your shoulder",
      "Digging your own grave",
      "Hanging by a thread",
      "Throwing caution to the wind",
      "Sticking your neck out",
      "Sweeping it under the rug",
      "Hitting the road",
      "Walking on thin ice",
      "Flying under the radar",
      "Tying the knot",
      "Cutting corners",
      "Stepping up to the plate",
      "Biting the bullet",
      "Making waves",
      "Getting cold feet",
      "Rocking the boat",
      "Testing the waters",
      "Opening a can of worms",
      "Cutting to the chase",
      "Picking up the pieces",
      "Running around in circles",
      "Splitting hairs",
      "Eating humble pie",
      "Blowing hot and cold",
      "Shaking like a leaf",
      "Throwing your weight around",
      "Washing your hands of something",
      "Breaking the bank",
      "Chewing the fat",
      "Jumping the gun",
      "Driving up the wall",
      "Eating someone alive",
      "Fanning the flames",
      "Giving the cold shoulder",
      "Hitting a wall",
      "Jumping through hoops",
      "Knocking it out of the park",
      "Laughing your head off",
      "Making a big splash",
      "Milking it for all it's worth",
      "Pulling a rabbit out of a hat",
      "Pushing the envelope",
      "Ruffling feathers",
      "Running out of steam",
      "Showing your true colors",
      "Spreading your wings",
      "Standing on your toes",
      "Stealing the show",
      "Throwing down the gauntlet",
      "Turning over a new leaf",
      "Walking a tightrope",
      "Wearing many hats",
      "Wiping the slate clean",
      "Add fuel to the fire",
      "At the drop of a hat",
      "Back to square one",
      "Barking up the wrong tree",
      "Beat around the bush",
      "Bite off more than you can chew",
      "Blow off some steam",
      "Break the mold",
      "Burst your bubble",
      "By the skin of your teeth",
      "Call it a day",
      "Cast the first stone",
      "Chip off the old block",
      "Close but no cigar",
      "Cold as ice",
      "Cook up a storm",
      "Cry over spilled milk",
      "Curiosity killed the cat",
      "Cut and dry",
      "Devil's advocate",
      "Dodge a bullet",
      "Don't cry wolf",
      "Drop the ball",
      "Eager beaver",
      "Eat your words",
      "Face the music",
      "Feather in your cap",
      "Fight tooth and nail",
      "Fit as a fiddle",
      "Flip the script",
      "Fly by the seat of your pants",
      "Go the extra mile",
      "Golden opportunity",
      "Grain of salt",
      "Green thumb",
      "Hang in there",
      "Happy as a clam",
      "Have a cow",
      "Have your cake and eat it too",
      "Head over heels",
      "Heart of gold",
      "Hit the sack",
      "Hold your horses",
      "Hot potato",
      "In the same boat",
      "Jack of all trades",
      "Jump to conclusions",
      "Keep your chin up",
      "Kill two birds with one stone",
      "Lay down the law",
      "Let bygones be bygones",
      "Live and let live",
      "Make ends meet",
      "Make hay while the sun shines",
      "Miss the boat",
      "Not playing with a full deck",
      "Off the beaten path",
      "Once in a blue moon",
      "Out of the frying pan into the fire",
      "Piece of cake",
      "Pull yourself together",
      "Rain on your parade",
      "Reap what you sow",
      "Rise and shine",
      "Shoot for the stars",
      "Skeletons in the closet",
      "Snug as a bug in a rug",
      "Spill the tea",
      "Stay on your toes",
      "Strike while the iron is hot",
      "Take it with a grain of salt",
      "The ball is in your court",
      "The calm before the storm",
      "The icing on the cake",
      "Throw a wrench in the works",
      "Time flies when you're having fun",
      "Turn the tables",
      "Under the weather",
      "Water under the bridge",
      "When pigs fly",
      "Wild goose chase",
      "You can't judge a book by its cover",
      "Zip your lip",
    ],
  },
  {
    id: "custom",
    name: "🎯 Custom",
    prompt: "",
  },
] as const;

export const getRandomOptionsForCategory = (
  categoryId: string,
  count: number
): string[] => {
  if (categoryId === "misc") {
    // For misc, get random options from all categories that have options
    const allOptions = CATEGORIES.filter(
      (cat) => cat.options && cat.id !== "misc" && cat.id !== "custom"
    ).flatMap((cat) => cat.options!);
    return shuffleArray([...allOptions]).slice(0, count);
  }

  if (categoryId === "custom") {
    return [];
  }

  const category = CATEGORIES.find((cat) => cat.id === categoryId);
  const categoryOptions = category?.options || [];
  return shuffleArray([...categoryOptions]).slice(0, count);
};

const shuffleArray = <T>(array: T[]): T[] => {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
};

// Export for use in other files
export const ALL_CATEGORIES = CATEGORIES;
